### ISSUE TITLE
[Bug] Games wont launch without internet

### ISSUE THREAD

**Issue by TheBlueOompaLoompa** [redromnon/HeroicBashLauncher#105]
### Before posting this issue, make sure you've read the [Issues section in the Readme](https://github.com/redromnon/HeroicBashLauncher#issues-and-suggestions) and the [Flatpak/Steam-Deck guide](https://github.com/redromnon/HeroicBashLauncher/wiki/Steam-Deck-(Flatpak)-Guide).

**Describe the bug**
Heroic bash launcher doesn't handle offline mode, when I try to  run a game offline, it just says check the logs.

**To Reproduce**
1. Go to steam, launch a heroic bash launcher game without internet
2. See error

**Expected behavior**
I expected the game to launch in offline mode like normal

**Details**

 - Platform: Steam Deck
 - OS: Steamos Holo
 - Heroic Version: Flatpak 2.4.3
 - Bash Launcher Version: 2.9.2 AppImage

**Additional context**
Launching through heroic does work offline.

**Comment by redromnon** [comment]
I've already applied the fix and will be included in the next release. Feel free to try out this build in the meantime - https://github.com/redromnon/HeroicBashLauncher/actions/runs/2994010487

**Comment by TheBlueOompaLoompa** [comment]
Yep, the new build works for me. Thank you!
