### ISSUE TITLE
[Bug] GOG game generates error message when launched via Steam only

### ISSUE THREAD

**Issue by theSt33v** [redromnon/HeroicBashLauncher#110]
Steps to reproduce:

1. On Steam Deck, install Stardew Valley GOG, Linux version via Heroic Flatpak version 2.4.3.
2. Start game from Heroic (works with no issues).
3. Use HBL version 2.9.2 to generate shortcut.
4. Start from Steam. The game appears to work with no issues but once the game is closed, an error shows up that says the game failed to launch (it didn't) and to check HBL log (attached).
[StardewValley_Heroic.log](https://github.com/redromnon/HeroicBashLauncher/files/9726172/StardewValley_Heroic.log)

**Comment by theSt33v** [comment]
Thanks. I read that thread and used the Heroic add to steam function and that works perfectly.

**Comment by redromnon** [comment]
Can you do me a favor? Can you just launch the `.sh` file directly and check?

**Comment by theSt33v** [comment]
Yep. Launching this file results in the exact same behavior as launching from Steam.

**Comment by redromnon** [comment]
Hmmm... I going to have to check this once I find the time.

**Comment by redromnon** [comment]
Issue should be fixed in v3.0.0
