### ISSUE TITLE
[Bug] Color bars on videos in THPS 1+2

### ISSUE THREAD

**Issue by fr500** [redromnon/HeroicBashLauncher#113]
### Before posting this issue, make sure you've read the [Issues section in the Readme](https://github.com/redromnon/HeroicBashLauncher#issues-and-suggestions) and the [Flatpak/Steam-Deck guide](https://github.com/redromnon/HeroicBashLauncher/wiki/Steam-Deck-(Flatpak)-Guide).

**Describe the bug**
Launching the game from Heroic and from Steam shows different issues
On Heroic the splash videos show as white:

![image](https://user-images.githubusercontent.com/1721040/201824145-c446173b-1c7f-4490-b194-33daef2044a6.png)

When I launch from steam they show as colored bars:

![image](https://user-images.githubusercontent.com/1721040/201824190-6418d67a-e068-4ab2-bd78-e14906c8fd50.png)

**Expected behavior**
Ideally videos should play, but I'd like to address this different behavior first and try to find how to fix it

**Details**

 - Platform: Steam Deck both Game mode and Desktop mode
 - Heroic Version: Flatpak
 - Bash Launcher Version: 3.0.1

**Additional context**

**Comment by fr500** [comment]
I checked the running processes with ps and it looks like the parameters are identical: 

```
/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton run /home/deck/Games/Heroic/TonyHawksProSkater/THPS12.exe -AUTH_LOGIN=unused -AUTH_PASSWORD=redacted -AUTH_TYPE=exchangecode -epicapp=Guppy -epicenv=Prod -epicovt=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/legendary/tmp/deab864e1abf4357b303bcd5ff6fe8da1a40708749eb41958c568b0638247eb1.ovt -EpicPortal -epicusername=Radius44 -epicuserid=977fcb3da8e241689a7f841a5a7bfb9e -epiclocale=en -epicsandboxid=deab864e1abf4357b303bcd5ff6fe8da
```

```
/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton run /home/deck/Games/Heroic/TonyHawksProSkater/THPS12.exe -AUTH_LOGIN=unused -AUTH_PASSWORD=redacted -AUTH_TYPE=exchangecode -epicapp=Guppy -epicenv=Prod -epicovt=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/legendary/tmp/deab864e1abf4357b303bcd5ff6fe8da1a40708749eb41958c568b0638247eb1.ovt -EpicPortal -epicusername=Radius44 -epicuserid=977fcb3da8e241689a7f841a5a7bfb9e -epiclocale=en -epicsandboxid=deab864e1abf4357b303bcd5ff6fe8da
```

So there must be some environment variable causing this

**Comment by redromnon** [comment]
By the way, Heroic has its own "Add to Steam" feature now.

**Comment by fr500** [comment]
Is that available on the flatpak now?

**Comment by fr500** [comment]
HGL without prefer system libraries
```
LD_LIBRARY_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-34/lib:/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-34/lib64: PULSE_LATENCY_MSEC=60 WINEPREFIX=/home/deck/Games/Heroic/Prefixes/TonyHawksProSkater /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Guppy --language en  --wine /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-34/bin/wine --wine-prefix /home/deck/Games/Heroic/Prefixes/TonyHawksProSkater
```

HBL
```
PULSE_LATENCY_MSEC=60 LD_PRELOAD= /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Guppy --language en --wine /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-34/bin/wine --wine-prefix "/home/deck/Games/Heroic/Prefixes/TonyHawksProSkater"
```

**Comment by redromnon** [comment]
> Is that available on the flatpak now?

It's been there since the 2.4.0 I guess.

**Comment by redromnon** [comment]
I'll add the Prefer System Libraries setting detection as discussed on Discord. 

Maybe you cam test it then.

**Comment by redromnon** [comment]
I've added the check for Prefer System Libraries. Can you test if it works? 

https://github.com/redromnon/HeroicBashLauncher/actions/runs/3486772425

Download the build and replace it with the existing executable.

**Comment by redromnon** [comment]
This issue should be fixed in the latest release.
