### ISSUE TITLE
[Bug] Failed to add artwork (running HeroicBashLauncher for the first time)

### ISSUE THREAD

**Issue by dausruddin** [redromnon/HeroicBashLauncher#115]
**Describe the bug**
I am installing HeroicBashLauncher on my SteamDeck. The guide asked me to launch `HeroicBashLauncher` after installing a game in Heroic Launcher.
I did that, however I am greeted with an error instead.

Log as follows:
```
[INFO] Using Bash Launcher v3.1.0
NOTE - This is an independent project and not affiliated with Heroic Games Launcher.

[DEBUG] Starting new HTTPS connection (1): api.github.com:443
[DEBUG] https://api.github.com:443 "GET /repos/redromnon/HeroicBashLauncher/releases/latest HTTP/1.1" 200 1549
[INFO] Done! Now creating launch files for your Epic Games library ...
[INFO] Sonic Mania [818447bb519b46d48d365d5753362796]...
[WARNING] shortcuts.vdf already exists in 1215400952
[INFO] Adding Sonic Mania to Steam
[INFO] Steam AppID for Sonic Mania is 2493287133
[INFO] Checking Artwork...
[INFO] Downloading Cover Art from https://cdn1.epicgames.com/salesEvent/salesEvent/EGS_SonicMania_Lab42_S6-510x680-b83646998d6a711b6997e076e091c015_510x680-b83646998d6a711b6997e076e091c015
[INFO] Downloading Background Art from https://cdn1.epicgames.com/salesEvent/salesEvent/EGS_SonicMania_Lab42_S5-1360x765-31b5379f91e2451e57e0273339bf68b8_1360x765-31b5379f91e2451e57e0273339bf68b8
[INFO] Downloading BigPicture Art from https://cdn1.epicgames.com/salesEvent/salesEvent/EGS_SonicMania_Lab42_S5-1360x765-31b5379f91e2451e57e0273339bf68b8_1360x765-31b5379f91e2451e57e0273339bf68b8
[CRITICAL] Traceback (most recent call last):
  File "func/artwork.py", line 114, in addartwork
KeyError: 'art_logo'
```

**To Reproduce**
1. Install Heroic Launcher
2. Extract HeroicBashLauncher per guide
3. Install a game. I installed Sonic Mania from Epic.
4. Run `HeroicBashLauncher` executable

**Expected behavior**
Greeted with `Process Finished` dialog

**Screenshots**
Not the best quality as I'm taking this with a camera
![IMG_20221203_192428_346](https://user-images.githubusercontent.com/5763466/205438560-7519edf9-597b-4787-9d5b-04bd3c5ab91e.jpg)

**Details**

 - Platform: Steam Deck
 - OS: SteamOS
 - Heroic Version: Flatpak 2.5.0
 - Bash Launcher Version: Downloaded the zip file, 3.1.0

**Additional context**
I have ran the executables a few times already. But still I consider everytime is my first time as I am trying to install it.

**Comment by redromnon** [comment]
Nice catch there! Looks like Heroic has updated the config files from where Bash Launcher reads from.

I'll try to fix this.

**Comment by redromnon** [comment]
You can use Heroic's built-in Add to Steam feature instead. It's more optimized.
