### ISSUE TITLE
[bug] Error message when trying to run HeroicBashLauncher binary with GoG games installed

### ISSUE THREAD

**Issue by aarron-lee** [redromnon/HeroicBashLauncher#12]
# Description

When attempting to run the HeroicBashLauncher with a GoG game installed in the Heroic Games Launcher,  I get prompted with a `Make sure you are running Heroic and try again` prompt. Once I uninstall the GoG game, it runs without any issues. No GOG .sh files are present in the `GameFiles` directory

# Launcher info

Heroic Games Launcher v2.2.1 AppImage (Legendary binary manually specified in settings)
HeroicBashLauncher v2.0
Legendary 0.20.25

# Machine Info

PopOS 21.10, kernel 5.16
Ryzen 5980hs, Nvidia 3050ti

# When run in Terminal

```bash
$ ./HeroicBashLauncher

Checking if Zenity is installed:
3.32.0

Cleaning left over game files if any...
sh: 1: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary: not found


Done! Now creating launch files for your Epic Games library ...

Cris Tales [e7d92786abe54fae9319c1ddb94ae271]...



Done! Now creating launch files for your GOG library ...

Journey to the Savage Planet [1519147341]...

# error prompt here,  after clicking ok in error prompt, it exits
```

# Video of bug

CrisTales is from Epic Games
Journey to the Savage Planet is from GOG

https://user-images.githubusercontent.com/9145965/156679150-89e41b39-955b-421c-a05d-a002c032d558.mp4

**Comment by redromnon** [comment]
I'll look into it.

**Comment by redromnon** [comment]
I've published a new release that should fix the bug. Do let me know if it works out for you.

**Comment by aarron-lee** [comment]
No longer has the reported error, but now there's a different error.

The resulting `.sh` script file doesn't launch the game, it errors out instead. Tested with 2 different GOG games.

Game itself works fine when launched within the Heroic Game Launcher.

Game: GOG version of YS VIII

Screenshot:
![image](https://user-images.githubusercontent.com/9145965/156770122-1449f3a4-97b6-4844-a728-1145ba49cf9f.png)

**Comment by redromnon** [comment]
Looks like an error with Heroic's gogdl binary. Bash Launcher gives out this error whenever launching fails. Can you post the contents of the launch script?

**Comment by aarron-lee** [comment]
Content of sh file:

```sh
#!/bin/bash 

#Game Name = Ys VIII: Lacrimosa of DANA

#App Name (Legendary) = 1622206415

#Overrides launch parameters
cd .. && ./HeroicBashLauncher "Ys VIII: Lacrimosa of DANA" "1622206415" "/home/aarronlee/.config/heroic/GamesConfig/1622206415.json" "gog-win" 



(STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/aarronlee/.steam/steam STEAM_COMPAT_DATA_PATH='/home/aarronlee/Games/Heroic/Prefixes/Ys-VIII-Lacrimosa-of-DANA' '/home/aarronlee/Games/legendary/legendary' launch "/home/aarronlee/Games/Heroic/Ys VIII - Lacrimosa of DANA" 1622206415 --no-wine --wrapper "'/home/aarronlee/.steam/root/compatibilitytools.d/Proton-6.21-GE-2/proton' run" --os windows || (echo "---CANNOT CONNECT TO NETWORK. RUNNING IN OFFLINE MODE---" ; STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/aarronlee/.steam/steam STEAM_COMPAT_DATA_PATH='/home/aarronlee/Games/Heroic/Prefixes/Ys-VIII-Lacrimosa-of-DANA' '/home/aarronlee/Games/legendary/legendary' launch "/home/aarronlee/Games/Heroic/Ys VIII - Lacrimosa of DANA" 1622206415 --offline --no-wine --wrapper "'/home/aarronlee/.steam/root/compatibilitytools.d/Proton-6.21-GE-2/proton' run" --os windows )) || (zenity --error --title="Error" --text="Failed to launch games. Consider posting the log as an issue" --width=200 --timeout=3)
```

> Also, can you also try installing a small game like OpenTTD and see if that works?

Let me try now, not sure if I have any small games on GOG.

**Comment by redromnon** [comment]
`"/home/aarronlee/Games/Heroic/Ys VIII - Lacrimosa of DANA"` maybe the issue. Can you compare this with the installed game's folder name?

**Comment by redromnon** [comment]
Got the issue - `'/home/aarronlee/Games/legendary/legendary'` It's using legendary instead of gog which is not supposed to happen. I'll have to make changes to the code again.

**Comment by aarron-lee** [comment]
> Got the issue - `'/home/aarronlee/Games/legendary/legendary'` It's using legendary instead of gog which is not supposed to happen. I'll have to make changes to the code again.

Ah just to clarify, I've manually downloaded + set the legendary binary in the Heroic Games Launcher. I have the binary itself at the `/home/aarronlee/Games/legendary/legendary` path

**Comment by redromnon** [comment]
That's fine. It should work for Epic games. Try removing the legendary binary (**Choose an Alternative Legendary Binary (restart required)** should say Using built-in binary) and launch the games while Heroic is running. You only need legendary if you have any Epic games installed.

**Comment by redromnon** [comment]
I forgot to add a condition that says "Use the alternate legendary binary if specified and if it is an Epic game". But instead, it says, "Just use the alternate binary is specified" meaning it will apply the alternate legendary binary to all games - Epic or GOG.

**Comment by redromnon** [comment]
Can you check if the Epic games launch while Heroic is running?

**Comment by aarron-lee** [comment]
> Can you check if the Epic games launch while Heroic is running (without alternate binary)? Because it is supposed to.

Ah ok, so I can confirm that without the alternate binary installed, Epic games launch while the Heroic Game Launcher is open. Same for GOG.

I wonder if this means that Heroic Game Launcher will also need an alternate gogdl binary option :thinking:

**Comment by aarron-lee** [comment]
Update: I tried manually pulling the gogdl binary out from the latest Heroic Game Launcher tar file, and manually updated the .sh files with the path of the binary.

Unsurprisingly, it worked fine. I guess it works for now as a workaround.

Maybe you can add a manual binary option to Heroic Bash Launcher for now?

**Comment by redromnon** [comment]
> > I forgot to add a condition that says "Use the alternate legendary binary if specified and if it is an Epic game". But instead, it says, "Just use the alternate binary is specified" meaning it will apply the alternate legendary binary to all games - Epic or GOG.
> 
> Makes sense to me. I can confirm that without the alternate binary, the GOG games launch fine. The Epic Store games stop working until I specify the alternate binary again.

The alternate legendary binary bug should be fixed in the latest release.
