### ISSUE TITLE
[Steam Deck] Error when only GOG games are installed

### ISSUE THREAD

**Issue by montogeek** [redromnon/HeroicBashLauncher#13]
Hi!

Thanks for your effort creating this nice piece of software, I am trying to follow [this ](https://www.gamingonlinux.com/2022/03/heroic-games-launcher-now-works-nicely-on-steam-deck/) guide to run Heroic (GoG) games as Non-Steam games on my Steam Deck when using the Steam Deck UI (no desktop mode).

I downloaded the Heroic Launcher as a AppImage, saved in Downloads, I opened from this folder and it does open without problem and I was also able to install Cyberpunk 2077, it runs and plays just fine in desktop mode.

I also downloaded the latest legendary binary and update Heroic settings to use it.

But now I want to run it from the Steam Deck UI, for that I would need to add it a Non-Steam Deck, there is where this project comes into the picture.

I downloaded the latest version 2.0.1, unzip it, marked it as executable, but when try to run it again (with Heroic Launcher running in the background), it always throw the error:
```
Looks like you have not installed Heroic Games Launcher or installed any game\n\nPlease consider doing so and try again
```

Checking the source code: https://github.com/redromnon/HeroicBashLauncher/blob/main/func/HeroicBashLauncher.py
It seems that it is correctly detecting that I have `zenity` installed but it is not detecting the legendary JSON config file.

How can I create this file and with which contents?

Thanks!

**Comment by montogeek** [comment]
Ah, just found an example of a config file (https://github.com/derrod/legendary#config-file), will try to create it manually and see how it goes.

**Comment by montogeek** [comment]
I found its structure https://github.com/derrod/legendary/blob/a25de242d964342cbd510c53c0cfbcaba7c1654b/legendary/models/game.py#L156 but not sure how to get that info for Cyberpunk 2077.

**Comment by redromnon** [comment]
Firstly, thanks a lot for your appreciation for my project.

I think I know what the issue. The source in https://github.com/redromnon/HeroicBashLauncher/blob/main/func/HeroicBashLauncher.py assumes you have at least one Epic game installed. But here, you just have a GOG game installed, am I right?

**Comment by montogeek** [comment]
Yes, I have no Epic games installed, I can try and install one :)

**Comment by redromnon** [comment]
Can try and install a Epic game? It should work then.

**Comment by montogeek** [comment]
Good news is that it works in Desktop mode, but it doesn't in Deck UI mode, it shows the same error, which makes sense because Heroic Launcher is not running.

**Comment by redromnon** [comment]
The bug should be fixed in the new release for GOG-only users.
