### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by ankushg** [redromnon/HeroicBashLauncher#14]
I tried running this on macos and ran into issues

It looks like the script hardcodes the paths for `legendary` and `gogdl` to be in `/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/`

On macOS, this isn't the case. They're actually in `/Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/`

**Comment by redromnon** [comment]
This project was specifically made with Linux in mind. Never thought of supporting macOS.

But it feels good to know that a macOS user is interested in the tool. It's just that I can't support it right away but might be able to sometime in the future considering the fact that macOS supports bash scripts too.

**Comment by redromnon** [comment]
So I was just curious to know how you would be making use of the launch scripts in macOS, since I'm thinking about bringing support to macOS. Like is there a frontend launcher you're using?

**Comment by redromnon** [comment]
I've decided not to support macOS.
