### ISSUE TITLE
Does not work with the Flatpack of Heroic

### ISSUE THREAD

**Issue by P-C-R** [redromnon/HeroicBashLauncher#17]
Does not work with it. It always says not installed. even if heroic is running

**Comment by redromnon** [comment]
I haven't added Flatpak support yet.

**Comment by P-C-R** [comment]
Ok. Would be nice for all the steam deck users ;)


Best

Rishabh M ***@***.***> schrieb am Fr., 11. März 2022, 10:22:

**Comment by damonsk** [comment]
directories if interested

/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/

**Comment by redromnon** [comment]
> directories if interested
> 
> /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/
> 
> /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/
> 
> /home/deck/.var/app/com.heroicgameslauncher.hgl/config/legendary/

I'm already aware of this and currently working on it. Thanks anyway!

**Comment by redromnon** [comment]
Flatpak support has been added to Bash Launcher v2.2.0
