### ISSUE TITLE
Still unable to launch on Steam Deck

### ISSUE THREAD

**Issue by mr-bobdobalina** [redromnon/HeroicBashLauncher#20]
If I run the .sh file alone I get:
bwrap: execvp ./HeroicBashLauncher: No such file or directory
bwrap: execvp ./Downloads/HeroicBashLauncher-2.2.2_Flatpak/GameFiles/HeroicBashLauncher: No such file or directory

This is with version 2.2.2 

The AddToSteam does work but doesn't launch the game.

**Comment by redromnon** [comment]
Geez, I've got no idea how to make this work. If only I had a Deck to test on. I believe it's working fine for other Deck users.
Try pasting the following code in any game's sh file and let me know the output -
```
#!/bin/bash

#Game Name = Kingdom New Lands (EPIC) 

#App Name = cacao

#Override launch parameters and launch game
flatpak run --command=pwd com.heroicgameslauncher.hgl 
```
The AddToSteam doesn't launch the game, it just adds the game to Steam.

**Comment by redromnon** [comment]
By the way, are you using Heroic via Flatpak? If you are, make sure you are using the Bash Launcher's Flatpak.zip

**Comment by redromnon** [comment]
I believe it's working for some other Deck users. Try pasting the following code in any game's sh script and let me know the output -
```
#!/bin/bash

#Game Name = Kingdom New Lands (EPIC) 

#App Name = cacao

#Override launch parameters and launch game
flatpak run --command=pwd com.heroicgameslauncher.hgl 
```

**Comment by mr-bobdobalina** [comment]
/home/deck

What I meant by the AddToSteam not working was that the shortcuts were added in Steam successfully but were still not able to launch the game (From Steam)

Yes I believe this is the Flatpak version of HGL. It is the one available from the Discover app explorer.

**Comment by mr-bobdobalina** [comment]
Maybe you could install SteamOS to help in your troubleshooting?

https://store.steampowered.com/steamos/buildyourown

**Comment by redromnon** [comment]
Ok, that's fine.
So I've got no idea as to why it isn't working.

**Comment by redromnon** [comment]
> Maybe you could install SteamOS to help in your troubleshooting?
> 
> https://store.steampowered.com/steamos/buildyourown

I'm afraid it's not Steam 3.0. It's the older one based on Debian.

**Comment by outphase** [comment]
To avoid the `bwrap: execvp ./HeroicBashLauncher: No such file or directory` error, you must use Flatseal to add "~/Downloads" to the permitted disk access locations for Heroic Games Launcher.

**Comment by outphase** [comment]
AddToSteam.sh causes the .sh to be added in a malformed target.

It should be `.../GameFiles/GameName_Heroic.sh`, but what is added to steam is `.../GameFilesGameName_Heroic.sh` -- it's missing the / between GameFiles and the .sh.

**Comment by mr-bobdobalina** [comment]
Thank you @outphase that worked! @redromnon maybe make a big notice in the release documentation for this so n00bs like me stop making bug reports! :)
