### ISSUE TITLE
Steam Deck Script Crash

### ISSUE THREAD

**Issue by Battleangel** [redromnon/HeroicBashLauncher#22]
HeroicBashLauncher-2.2.3_AppImage.zip
Heroic-2.2.6.AppImage

**Console Output:**
```
Checking if Zenity is installed:

(process:3647): Gtk-WARNING **: 17:54:47.437: Locale not supported by C library.
        Using the fallback 'C' locale.
3.32.0

Cleaning left over game files if any...
[cli] INFO: Cleanup complete! Removed 0.00 MiB.


Done! Now creating launch files for your Epic Games library ...

Traceback (most recent call last):
  File "HeroicBashLauncher.py", line 21, in <module>
  File "listinstalled.py", line 67, in listinstalled
  File "json/__init__.py", line 293, in load
  File "encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1991: ordinal not in range(128)
[3646] Failed to execute script 'HeroicBashLauncher' due to unhandled exception!
```

**SteamOS:**

```
Operating System: SteamOS snapshot
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-valve10.1-1-neptune-02144-g7fffaf925dfb (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Custom APU 0405
Memory: 14,5 GiB of RAM
Graphics Processor: AMD Custom GPU 0405
```

**Comment by Ilmadic** [comment]
I have the same issue but with the Flatpak version.

**Comment by redromnon** [comment]
```
File "json/__init__.py", line 293, in load
File "encodings/ascii.py", line 26, in decode
File "encodings/ascii.py", line 26, in decode
```
Do you have gog games in your library? If I'm not wrong, the above errors are caused by the gogdl binary used in Heroic since these .py files are not used in Bash Launcher. This is occuring when Heroic is trying to parse `heroic/gog_store/library.json`

**Comment by redromnon** [comment]
Are the games launching from Heroic Games Launcher?

**Comment by mr-bobdobalina** [comment]
Tetris runs fine from HGL, Tetris's full game name is "Tetris® Effect: Connected" So I guess the ® and/or : are issues.

**Comment by redromnon** [comment]
You're right. But I have no issues with Rocket League® when running Bash Launcher.

**Comment by Battleangel** [comment]
Hi 
these are the installed games, all of them from the Epic Store https://ibb.co/kGDpGSr

**Comment by redromnon** [comment]
> Hi these are the installed games, all of them from the Epic Store https://ibb.co/kGDpGSr

Looks fine. Do you have installed any GOG games?

**Comment by Battleangel** [comment]
Yes had in the Past for Testing it was Cyberpunk 2077 and there are 2 games installed via Downloaded .exe files from the GoG Page.

The Dig®
Indiana Jones® and the Fate of Atlantis™

**Comment by redromnon** [comment]
To make it clear, The Dig® & Indiana Jones® and the Fate of Atlantis™ show as installed in Heroic? Again, I feel those special characters like ® and ™ are causing the issue.

**Comment by Battleangel** [comment]
There are not in the Heroic installer but will uninstall them via the delivered sh script to test that out, just an moment ,)

**Comment by Ilmadic** [comment]
> > Hi these are the installed games, all of them from the Epic Store https://ibb.co/kGDpGSr
> 
> Looks fine. Do you have installed any GOG games?

I have Cyberpunk 2077 and Witcher 3 installed from GoG (with heroic). My epic games are working (.sh is created) but the script crash after it.

**Comment by redromnon** [comment]
Any GOG games installed via Heroic?

**Comment by redromnon** [comment]
Can you send your log too?

**Comment by Battleangel** [comment]
Deleted The Dig and Indiana Jones and removed all left files under /home/deck/GOG Games so there are only the 3 Epic Store games from the Pictures installed on my SteamDeck.


```
Checking if Zenity is installed:

(process:7215): Gtk-WARNING **: 06:37:56.025: Locale not supported by C library.
        Using the fallback 'C' locale.
3.32.0

Cleaning left over game files if any...
[cli] INFO: Cleanup complete! Removed 0.00 MiB.


Done! Now creating launch files for your Epic Games library ...

Traceback (most recent call last):
  File "HeroicBashLauncher.py", line 21, in <module>
  File "listinstalled.py", line 67, in listinstalled
  File "json/__init__.py", line 293, in load
  File "encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1991: ordinal not in range(128)
[7214] Failed to execute script 'HeroicBashLauncher' due to unhandled exception!

```

**Comment by redromnon** [comment]
Yeah, it still doesn't work because HBL looks in` library.json` for game names, where The Dig and Indiana Jones are present and are part of your GOG game account. It doesn't matter even if they are uninstalled.

I've got to make some changes in the code to make game names with special characters compatible.

**Comment by Ilmadic** [comment]
> Can you paste your log too?

`Checking if Zenity is installed:

(process:9756): Gtk-WARNING **: 07:10:42.901: Locale not supported by C library.
        Using the fallback 'C' locale.
3.32.0

Cleaning left over game files if any...
sh: line 1: /home/deck/Games/Launcher/HeroicBashLauncher-2.2.3_Flatpak/GameFiles/binaries/legendary: No such file or directory


Done! Now creating launch files for your Epic Games library ...

Absolute Drift [19927295d6e3467887d4e830d8c85963]...

Rise of the Tomb Raider: 20 Year Celebration [f7cc1c999ac146f39b356f53e3489514]...

Traceback (most recent call last):
  File "HeroicBashLauncher.py", line 21, in <module>
  File "listinstalled.py", line 67, in listinstalled
  File "json/__init__.py", line 293, in load
  File "encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4991: ordinal not in range(128)
[9755] Failed to execute script 'HeroicBashLauncher' due to unhandled `exception!`

**Comment by redromnon** [comment]
Yep, same thing

**Comment by redromnon** [comment]
As a workaround, you can delete the special characters in the game names if you wish to (Like from Rocket League® to just Rocket League.)

For Heroic Epic games - go to `legendary/installed.json` and edit the 'title' of the that game
For Heroic GOG games - go to `heroic/gog_store/library.json` and edit the 'title' of that game

The issue might be solved temporarily until a fix arrives

**Comment by Ilmadic** [comment]
Thanks for the workaround. I changed all Titels of my installed games but I still get the same error. Should I change all Titels with special characters?

**Comment by redromnon** [comment]
Maybe try that too. I don't know if it is going to work or not since I haven't come across this issue in my case. If it doesn't work, you will have to wait for the fix.

**Comment by Ilmadic** [comment]
Doesn't work in my case. I'm waiting for a fix. Thanks for the help.
