### ISSUE TITLE
Issue launching from Steam

### ISSUE THREAD

**Issue by mr-bobdobalina** [redromnon/HeroicBashLauncher#23]
I am testing on Steam Deck with 2 games installed from HGL: Control and Tetris Effect Connected

Both games launch fine from the generated .sh files if run from CLI.  Both are added to Steam successfully but only Control launches successfully from Steam. Tetris will not launch, pressing Play just shows a quick 'preparing to launch' box then disappears quickly.

**Comment by redromnon** [comment]
Can you run `steam` from the terminal and launch Tetris? If you can, just paste the part of the log after you launch Tetris here, since the actual log will be a bit long.

**Comment by mr-bobdobalina** [comment]
(deck@steamdeck GameFiles)$ steam
steam.sh[26768]: Running Steam on steamos rolling 64-bit
steam.sh[26768]: STEAM_RUNTIME is enabled automatically
setup.sh[26846]: Steam runtime environment up-to-date!
steam.sh[26768]: Steam client's requirements are satisfied

Steam just opens up and I'm back in Terminal, I had to run /usr/bin/steam-jupiter to get a running log.

But here is what comes up when I run Tetris:

GameAction [AppID 3649103972, ActionID 2] : LaunchApp changed task to SynchronizingControllerConfig with ""

(steam:28053): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:28053): GLib-CRITICAL **: unquote_string_inplace: assertion `err == NULL || *err == NULL' failed
GameAction [AppID 3649103972, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 3649103972, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 3649103972, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 3649103972, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3649103972 -- "/home/deck/Downloads/HeroicBashLauncher-2.2.3_Flatpak/GameFiles/TetrisEffectConnected_Heroic.sh"\0
Game process added : AppID 0 "/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3649103972 -- "/home/deck/Downloads/HeroicBashLauncher-2.2.3_Flatpak/GameFiles/TetrisEffectConnected_Heroic.sh"", ProcID 28528, IP 0.0.0.0:0
chdir /home/deck/Downloads/HeroicBashLauncher-2.2.3_Flatpak/GameFiles/
GameAction [AppID 3649103972, ActionID 2] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

(steam:28053): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:28053): GLib-CRITICAL **: unquote_string_inplace: assertion `err == NULL || *err == NULL' failed
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

(steam:28053): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:28053): GLib-CRITICAL **: unquote_string_inplace: assertion `err == NULL || *err == NULL' failed
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Checking if Zenity is installed:
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Gtk-Message: 20:25:03.956: Failed to load module "canberra-gtk-module"
3.32.0
Traceback (most recent call last):
  File "HeroicBashLauncher.py", line 35, in <module>
  File "flatpak.py", line 29, in launchflatpakgame
  File "checkparameters.py", line 12, in checkparameters
  File "json/__init__.py", line 293, in load
  File "encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 333: ordinal not in range(128)
[3] Failed to execute script 'HeroicBashLauncher' due to unhandled exception!
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
bwrap: execvp ./Downloads/HeroicBashLauncher-2.2.3_Flatpak/GameFiles/HeroicBashLauncher: No such file or directory
Game process removed: AppID 0 "/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3649103972 -- "/home/deck/Downloads/HeroicBashLauncher-2.2.3_Flatpak/GameFiles/TetrisEffectConnected_Heroic.sh"", ProcID 28528 
ThreadGetProcessExitCode: no such process 28547
ThreadGetProcessExitCode: no such process 28543
ThreadGetProcessExitCode: no such process 28535
ThreadGetProcessExitCode: no such process 28530
ThreadGetProcessExitCode: no such process 28529
Uploaded AppInterfaceStats to Steam

(steam:28053): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:28053): GLib-CRITICAL **: unquote_string_inplace: assertion `err == NULL || *err == NULL' failed

**Comment by mr-bobdobalina** [comment]
Log when running Control (launches successfully)

(steam:28896): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:28896): GLib-CRITICAL **: unquote_string_inplace: assertion `err == NULL || *err == NULL' failed

(steam:28896): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:28896): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:28896): GLib-CRITICAL **: unquote_string_inplace: assertion `err == NULL || *err == NULL' failed

(steam:28896): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:28896): GLib-CRITICAL **: unquote_string_inplace: assertion `err == NULL || *err == NULL' failed
RegisterForAppOverview 1: 47ms
RegisterForAppOverview 2: 48ms

(steam:28896): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:28896): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:28896): GLib-CRITICAL **: unquote_string_inplace: assertion `err == NULL || *err == NULL' failed
Installing breakpad exception handler for appid(steam)/version(1647472031)
Installing breakpad exception handler for appid(steam)/version(1647472031)
Installing breakpad exception handler for appid(steam)/version(1647472031)

(steam:28896): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:28896): GLib-CRITICAL **: unquote_string_inplace: assertion `err == NULL || *err == NULL' failed

(steam:28896): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:28896): GLib-CRITICAL **: unquote_string_inplace: assertion `err == NULL || *err == NULL' failed
CAPIJobRequestUserStats - Server response failed 2

(steam:28896): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:28896): GLib-CRITICAL **: unquote_string_inplace: assertion `err == NULL || *err == NULL' failed
Installing breakpad exception handler for appid(steam)/version(1647472031)
Installing breakpad exception handler for appid(steam)/version(1647472031)
Installing breakpad exception handler for appid(steam)/version(1647472031)
Installing breakpad exception handler for appid(steam)/version(1647472031)
GameAction [AppID 2314081455, ActionID 1] : LaunchApp changed task to SynchronizingControllerConfig with ""

(steam:28896): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:28896): GLib-CRITICAL **: unquote_string_inplace: assertion `err == NULL || *err == NULL' failed
GameAction [AppID 2314081455, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 2314081455, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 2314081455, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 2314081455, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=2314081455 -- "/home/deck/Downloads/HeroicBashLauncher-2.2.3_Flatpak/GameFiles/Control_Heroic.sh"\0
Game process added : AppID 0 "/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=2314081455 -- "/home/deck/Downloads/HeroicBashLauncher-2.2.3_Flatpak/GameFiles/Control_Heroic.sh"", ProcID 29296, IP 0.0.0.0:0
chdir /home/deck/Downloads/HeroicBashLauncher-2.2.3_Flatpak/GameFiles/
GameAction [AppID 2314081455, ActionID 1] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

(steam:28896): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:28896): GLib-CRITICAL **: unquote_string_inplace: assertion `err == NULL || *err == NULL' failed
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

(steam:28896): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

(steam:28896): GLib-CRITICAL **: unquote_string_inplace: assertion `err == NULL || *err == NULL' failed
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Checking if Zenity is installed:
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Gtk-Message: 20:34:56.760: Failed to load module "canberra-gtk-module"
3.32.0
Launch command:
STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH='/home/deck/Games/Heroic/Prefixes/Control' /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Calluna --no-wine --wrapper "'/home/deck/.steam/root/steamapps/common/Proton 7.0/proton' run" 
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[Core] WARNING: Could not determine locale, falling back to en-US
[cli] INFO: Logging in...
[Core] INFO: Logging in...
[cli] INFO: Checking for updates...
Installing breakpad exception handler for appid(steam)/version(1647472031)
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Calluna...
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 6 != 5, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API FAIL] SteamAPI_Init() failed
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
WARNING: radv is not a conformant Vulkan implementation, testing use only.

**Comment by redromnon** [comment]
```
File "json/init.py", line 293, in load
File "encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 333: ordinal not in range(128)
```

Looks similar to #22, so I'm closing this.

**Comment by Battleangel** [comment]
Deleted The Dig and Indiana Jones and removed all left files under /home/deck/GOG Games so there are only the 3 Epic Store games from the Pictures installed on my SteamDeck.


```
Checking if Zenity is installed:

(process:7215): Gtk-WARNING **: 06:37:56.025: Locale not supported by C library.
        Using the fallback 'C' locale.
3.32.0

Cleaning left over game files if any...
[cli] INFO: Cleanup complete! Removed 0.00 MiB.


Done! Now creating launch files for your Epic Games library ...

Traceback (most recent call last):
  File "HeroicBashLauncher.py", line 21, in <module>
  File "listinstalled.py", line 67, in listinstalled
  File "json/__init__.py", line 293, in load
  File "encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1991: ordinal not in range(128)
[7214] Failed to execute script 'HeroicBashLauncher' due to unhandled exception!

```
