### ISSUE TITLE
Failed to launch games with Wine-GE-Proton

### ISSUE THREAD

**Issue by JoshuaHasNoClue** [redromnon/HeroicBashLauncher#26]
When I try to run a game via the sh file, it gives me a prompt that says "Failed to launch Games"

I get this output when I run through the Terminal
https://gist.github.com/JoshuaHasNoClue/e9ca614a17b87e0209df0bfba92e192f

**Comment by redromnon** [comment]
Can you check if the Launch command is the same as the one in the Heroic's log?

**Comment by JoshuaHasNoClue** [comment]
It isn't the same

.sh file:
#Launch command = STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH='/run/media/mmcblk0p1/heroic/prefix/GhostRunner' /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/run/media/mmcblk0p1/heroic/Ghostrunner" 1957528513 --offline --no-wine --wrapper "'/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-6/bin/wine' run" --os windows 

Heroic:
Launch Command: "/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl" launch "/run/media/mmcblk0p1/heroic/Ghostrunner" 1957528513 --wine '/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-6/bin/wine' --wine-prefix '/run/media/mmcblk0p1/heroic/prefix/GhostRunner' --os windows

**Comment by JoshuaHasNoClue** [comment]
as you see, i am using proton ge downloaded from heroic. if i set the game to use proton from steam, it works

**Comment by redromnon** [comment]
So Bash Launcher is getting confused whether to use the Wine or Proton path, since the GE's new releases include both names.
