### ISSUE TITLE
Script Fails for GOG only games

### ISSUE THREAD

**Issue by simkid7** [redromnon/HeroicBashLauncher#27]
Receiving unhandled exception on Steam Deck. No Epic Games installed, just GOG. Enabled full User access in FlatSeal for Heroic Games Launcher. Only GOG game installed is Witcher 3. No sign of ASCII error. Unsure of following steps.

Cleaning left over game files if any...
sh: line 1: /home/deck/binaries/legendary: No such file or directory
Traceback (most recent call last):
  File "HeroicBashLauncher.py", line 21, in <module>
  File "listinstalled.py", line 24, in listinstalled
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.var/app/com.heroicgameslauncher.hgl/config/legendary/installed.json'
[16133] Failed to execute script 'HeroicBashLauncher' due to unhandled exception!

**Comment by simkid7** [comment]
Fixed error. Will not run unless an Installed.json exists for the Epic Games dirs (/home/deck/binaries/legendary and /home/deck/.var/app/com.heroicgameslauncher.hgl/config/legendary/installed.json)

Resolved by installing a free small game from Epic and script ran after. Would request putting in a skip for if a user does not have any Epic Games installed.

**Comment by redromnon** [comment]
Yeah, I forgot to add a simple check for that. Will implement it.

**Comment by phoenixcon** [comment]
This has been driving me crazy all day! Came here to report and glad to see someone else ran into it. I'm not crazy!

Thanks @simkid7 and @redromnon
