### ISSUE TITLE
Flatpak Version can't create working .sh Files

### ISSUE THREAD

**Issue by Schnubbirunkel** [redromnon/HeroicBashLauncher#30]
Using HeroicBashLauncher Flatpak version...

(process:22404): Gtk-WARNING **: 00:21:35.609: Locale not supported by C library.
	Using the fallback 'C' locale.
3.32.0
Traceback (most recent call last):
  File "HeroicBashLauncher.py", line 21, in <module>
  File "listinstalled.py", line 79, in listinstalled
  File "createlaunchfile.py", line 55, in createlaunchfile
UnicodeEncodeError: 'ascii' codec can't encode character '\xae' in position 967: ordinal not in range(128)
[22403] Failed to execute script 'HeroicBashLauncher' due to unhandled exception!
Checking if Zenity is installed:

**Comment by redromnon** [comment]
Are you using the Deck?
Is there a game or a folder (like prefix folder) that includes the ® symbol?

**Comment by Schnubbirunkel** [comment]
Yes that was it! I've uninstalled that game and installed another and everything worked great.

**Comment by redromnon** [comment]
So did any folder names related to the game have that character? Like wine prefix name, game folder name, etc. 

Because the program removes special characters for everything except names of folders related to the game since they are sensitive.

**Comment by Schnubbirunkel** [comment]
Yes it was a Indiana Jones game and it had the ® symbol in there.

**Comment by redromnon** [comment]
Can you confirm if the game's wine prefix name contains the symbol?

**Comment by Schnubbirunkel** [comment]
![20220404_140246](https://user-images.githubusercontent.com/35907349/161539730-f1431b31-3c27-4781-8677-310921d2555d.jpg)
Yes it's in there.

**Comment by redromnon** [comment]
I can't do anything about this, it's how Heroic assigns the names to the wine prefixes.

But what you can do is delete special characters like ® and try running Bash Launcher again.
