### ISSUE TITLE
Script fails to add games to Steam

### ISSUE THREAD

**Issue by woltersdylan** [redromnon/HeroicBashLauncher#31]
I followed the steps described in the wiki for Flatpak use on Steamdeck. It managed to create the script for the game i have installed, but it fails to add the actual item to Steam. The error message points me to the logs, which only acknowledges that it found the game and says nothing else (no errors). I directly launched the script in terminal and there was still no output there, nor in the log file. The message in question said to consider reporting it here, so I thought I'd do so. 

How can I help find more helpful information to debug the issue?

**Comment by redromnon** [comment]
Did it show the "Failed to add game to Steam" dialog?
Also can you check if there's a shorcuts.vdf file in `.steam/steam/userdata/<your_appid>/config`?
