### ISSUE TITLE
Kingdom Come Deliverance does not work through SteamDeck UI

### ISSUE THREAD

**Issue by hftl-kalle** [redromnon/HeroicBashLauncher#32]
Greetings

As my log is different than that of the other thread I thought my issue warrants a different issue.
I am using HBL 2.3.0-Flatpak
Running in Heroic works fine.
Running HeroicBashLauncher script from Deskmode works fine. 
SteamDeck GameMode does not work.

I also tried banished but there everything works and the script file looks really similar.

> /home/deck/.local/share/Steam/steamapps/compatdata/3008463529/pfx/dosdevices/z:/home/deck/Games/HeroicBashLauncher-2.3.0_Flatpak/GameFiles/KingdomComeDeliverance_Heroic.sh: line 11: flatpak: command not found
>pid 18614 != 18610, skipping destruction (fork without exec?)
>/home/deck/.local/share/Steam/steamapps/compatdata/3008463529/pfx/dosdevices/z:/home/deck/Games/HeroicBashLauncher-2.3.0_Flatpak/GameFiles/KingdomComeDeliverance_Heroic.sh: line 11: flatpak: command not found
>pid 18615 != 18610, skipping destruction (fork without exec?)

**Comment by redromnon** [comment]
So is this the log that you got in KingdomComeDeliverance.log? If there is more, try pasting them too.

**Comment by hftl-kalle** [comment]
I removed all the connections in steam and cleared the shell scripts and ran setup again. That seemed to have done it.
I was also wondering why the logs are almost empty. Who knows.
