### ISSUE TITLE
Rephrase step 5 of Steam Deck guide

### ISSUE THREAD

**Issue by eddiegalvez** [redromnon/HeroicBashLauncher#33]
In Flatseal, enable the All user files or set the path to the HeroicBashLauncher directory in Other files under Filesystem for Heroic Games Launcher.

It will be much clearer written as such:

In Flatseal, select the _Heroic Games Launcher_ flatpak and allow it to access the directory Bash Launcher is in; under _Filesystem_, either add the HeroicBashLauncher directory as a new _Other files_ entry, or simply toggle the _All user files_ option for simplicity.

What happened is when I was following this guide, the top line, while very short, leaves "under Filesystem for Heroic..." LAST, and yet if you have no idea what this is or why... you're reading to enable something... as if it was a Flatseal option.

**Comment by redromnon** [comment]
Will change.
