### ISSUE TITLE
Script creates one shortcut, then fails (possible issue with cover art implementation)

### ISSUE THREAD

**Issue by xhoneybear** [redromnon/HeroicBashLauncher#34]
I've been looking around but I can't find any issue that could be similar...

I just downloaded a bunch of games I have on my Epic account through Heroic (Flatpak version) and I wanted to use the script (v2.4.0, Flatpak version of course) to make myself neat Steam shortcuts for the Deck mode. However, the script only generates a script for one game (Cave Story+) and successfully adds it to Steam shortcuts (and it works flawlessly, no background image though), but then doesn't generate any scripts for other games and throws "Failed to add games to Steam". Script log ends with the verbose of Cave Story shortcut being added. It's bugging me because I tried closing Steam multiple times, relogging, removing the generated script, removing shortcuts.vdf file (that only made it worse though), to no avail. Permissions in Flatseal are set to allow whole user folder access, so it's definitely not that either...

EDIT: curiously enough I checked and there's no _heroic_ folder in the _.config_ directory, even when I manually created it and reinstalled a game Heroic made no files there. there was no permission or order to create such folder when I looked into Flatseal so I wonder if it's normal or abnormal and might it be the cause of my issue?

**Comment by xhoneybear** [comment]
Update: I just installed version 2.3.0 instead of 2.4.0 and it worked flawlessly :) There must be an issue with image parsing for the cover arts, since that's probably the only change that could possibly cause issues, and as I mentioned the Cave Story shortcut that worked still didn't have a cover pic on the shortcut, so it probably failed right there

**Comment by redromnon** [comment]
Yeah, it's definitely something to do with the image. I'll see what I can do.

**Comment by redromnon** [comment]
Can you try using [v2.4.1](https://github.com/redromnon/HeroicBashLauncher/releases) and see you can spot any errors in the log?

**Comment by xhoneybear** [comment]
Yes, just did that and the issue is the "grid" folder being absent! It's not in the directory by default unless you have manually added artwork to your shortcuts before, so I would suggest adding a function to check if the folder exists and create one if it does not. I created a pull request with a fix, I am not really great at coding but I hope it's good and works :)

**Comment by redromnon** [comment]
No problem! Your PR does the job.
