### ISSUE TITLE
EGS method of launching game seems to break

### ISSUE THREAD

**Issue by koozietime** [redromnon/HeroicBashLauncher#39]
Not sure if this is just a quirk of the way that the Epic Game Store attempts to launch this particular game or if this is even appropriate to post for this repo so my apologies ahead of time.

I’m trying to launch Kingdom Hearts 1.5 + 2.5 through the Heroic launcher. The way that EGS appears to try and do this is to launch a separate exe that is essentially just a menu to select which of the multiple included games you wish to launch. It will then launch the specific exe of the game you’ve selected. 

What happens on Deck is that I’m able to select my desired game and the “menu” launcher even closes like you’d expect in anticipation of launching the desired game. However it then just reopens without launching the selected game and returns me to the same menu. 

My best (uneducated) guess is that the launcher is unable to access the software it’s trying to launch. This persists in both the actual Heroic launcher as well as the Steam OS UI. I even gave Heroic access to the folder containing each individual game in Flatseal but nothing changed.

**Comment by redromnon** [comment]
You can specify an alternative exe path in Heroic's [Other] Game settings and see if that works.

**Comment by koozietime** [comment]
Interestingly that did allow me to skip straight to my desired game. I was able to proceed with the forced selection of game options (difficulty, etc.) before it attempted to start a new game… at which point it crashed. Seems to happen identically in both Heroic and Steam UI. Shoot.

**Comment by redromnon** [comment]
Looks like a Proton or game-specific issue. You should ask for help in Heroic's Discord channel.
