### ISSUE TITLE
Games not added to one account with multiple Steam logins on same Deck

### ISSUE THREAD

**Issue by Skatterd** [redromnon/HeroicBashLauncher#41]
Running the Flatpak version with two Steam accounts on the same Steam deck I'm getting the games added just fine for one user but not the other, no matter what I do or which user is logged in/out of Steam.

**Comment by redromnon** [comment]
I'm yet to implement support for users using multiple Steam accounts. There are two ways to make this happen -
1. Add scripts to all accounts
2. Let user decide the account for the scripts to be added

**Comment by redromnon** [comment]
As a workaround, you can create the shorcuts.vdf in the account you prefer and delete that same file in the other account.

**Comment by redromnon** [comment]
I've added multiple Steam account support in v2.5.0

**Comment by Skatterd** [comment]
> I've added multiple Steam account support in v2.5.0

Thank you!
