### ISSUE TITLE
gameoverlayrenderer.so error

### ISSUE THREAD

**Issue by A-w-x** [redromnon/HeroicBashLauncher#45]
ArchLinux
using appImage
fresh install, both os and launcher

steps:

./setup.sh
./Addtosteam.sh

run steam
press play

[RocketLeague_Heroic.log](https://github.com/redromnon/HeroicBashLauncher/files/8502573/RocketLeague_Heroic.log)

rocket league launcher script delete itself after the error

**Comment by redromnon** [comment]
I believe the some folder related to Rocket League has a registered symbol included (most likely the Wine prefix folder). Just remove that special character from the name and you're good to go. Your log file looks similar to See #30.

**Comment by A-w-x** [comment]
yes, there was a symbol but it still fails, this time it cannot find the path even if it is there (no symbols)

i have a shared ntfs partition, installed rocket from windows in that partition with egs, then imported the game in heroic in linux
prefix is in linux partition, game files are in ntfs partition
the game boots in heroic

[RocketLeague_Heroic.log](https://github.com/redromnon/HeroicBashLauncher/files/8505283/RocketLeague_Heroic.log)

launch script
```#!/bin/bash 

#Generate log
exec > logs/RocketLeague_Heroic.log 2>&1

#Game Name = Rocket League (EPIC) 

#App Name = Sugar

#Overrides launch parameters
cd .. && ./HeroicBashLauncher "Rocket League" "Sugar" "/home/user/.config/heroic/GamesConfig/Sugar.json" "epic" 

(STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/user/.steam/steam STEAM_COMPAT_DATA_PATH='/home/user/Games/Heroic/Prefixes/RocketLeague' /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --no-wine --wrapper "'/usr/share/steam/compatibilitytools.d/proton-ge-custom/proton' run" || (echo "---CANNOT CONNECT TO NETWORK. RUNNING IN OFFLINE MODE---" ; STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/user/.steam/steam STEAM_COMPAT_DATA_PATH='/home/user/Games/Heroic/Prefixes/RocketLeague' /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --offline --no-wine --wrapper "'/usr/share/steam/compatibilitytools.d/proton-ge-custom/proton' run" )) || (zenity --error --title="Error" --text="Failed to launch games 

Consider posting the log as an issue" --width=200 --timeout=3)
```
on top of this, it seems that if legendary package is not installed, the binaries directory is not populated, even if the script uses heroic built-in legendary bin

**Comment by redromnon** [comment]
You're using Bash Launcher AppImage right? Can you confirm if you have the following path - `/opt/Heroic/resources/app.asar.unpacked/build/bin/linux` on your system?

**Comment by A-w-x** [comment]
yes, appimage, and yes, path is there

**Comment by redromnon** [comment]
Just to make it clear, you're now using Heroic's AppImage version but before you were using Heroic via AUR?

**Comment by A-w-x** [comment]
no, i'm using this (bashlauncher) appimage
heroic: https://aur.archlinux.org/packages/heroic-games-launcher-bin

**Comment by redromnon** [comment]
So I don't think you're using Heroic's AppImage version. Although it won't make much of a difference, try using the base Bash Launcher version.
Can you also compare the launch command in Heroic's game log and the one in the launch script?

**Comment by A-w-x** [comment]
the base zip version complains about missing binaries when running from steam and it still does not boot
[RocketLeague_Heroic.log](https://github.com/redromnon/HeroicBashLauncher/files/8505478/RocketLeague_Heroic.log)

setup reports no error, but binaries folder is missing

heroic launch command

```Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/user/.steam/steam STEAM_COMPAT_DATA_PATH='/home/user/Games/Heroic/Prefixes/RocketLeague' /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --no-wine --wrapper "'/usr/share/steam/compatibilitytools.d/proton-ge-custom/proton' run"```

running the script from terminal it works

**Comment by redromnon** [comment]
The Rocket League script works from the terminal? But you also said Rocket League doesn't work.
I don't understand why the AppImage version sees `/opt/Heroic/resources/app.asar.unpacked/build/bin/linux` and the base version doesn't. They're essentially the same except the AppImage zip includes the binaries.

**Comment by A-w-x** [comment]
the script i just genereated works in terminal, but it does not work when i run it from steam and that log is the error when running from steam.

**Comment by redromnon** [comment]
I'm getting a little confused here. When you say you generated the script, did you create your own bash script and not Bash Launcher's? Is this the same scipt you used in Steam?

**Comment by A-w-x** [comment]
i run setup.sh and then Addtosteam.sh

setup.sh generates the script, thats the one i run from terminal and the one added in steam

**Comment by redromnon** [comment]
Okay, so you tried the generated script and it works from the terminal. Then you ran AddToSteam, selected Rocket League and it added that same script to Steam but it doesn't work. Am I correct?

**Comment by A-w-x** [comment]
yes

**Comment by redromnon** [comment]
Hmmm... Strange.

**Comment by redromnon** [comment]
> the base zip version complains about missing binaries when running from steam and it still does not boot [RocketLeague_Heroic.log](https://github.com/redromnon/HeroicBashLauncher/files/8505478/RocketLeague_Heroic.log)
> 

Is this the same log of the generated script?

**Comment by A-w-x** [comment]
this is what i get when i run it from steam

**Comment by A-w-x** [comment]
found the issue, i disabled the steam compatibility tool
not sure why the script has issues with it but my steam setting was proton-ge, and if i enable it, the script does not boot
it boots when disabled

**Comment by redromnon** [comment]
You don't need to use the steam compatibility tool since you're just running a bash script and not the "actual game". You only need to choose Wine or Proton in Heroic's settings, that is running the game.

**Comment by redromnon** [comment]
If you're no longer facing issues, please consider closing this.

**Comment by A-w-x** [comment]
it was my default setting in steam

**Comment by redromnon** [comment]
Ah okay. No problem.
