### ISSUE TITLE
Artwork got reset after reimport the games

### ISSUE THREAD

**Issue by githublsx** [redromnon/HeroicBashLauncher#46]
Hi, first thank you so much for making this tool, this is very helpful!

I noticed an issue that when I'm using the tool, it seems that after I imported the games into steam library and change the art for certain games, and reimport the games, those artworks will be reset to original ones, maybe we can add another extension check for png files in checkartworkexists function to fix it? Thank you!

**Comment by redromnon** [comment]
The program only checks if images already exist in jpg format. I'll implement checking for those stored in png format.

**Comment by githublsx** [comment]
Thank you!
