### ISSUE TITLE
All non-steam app icons are reset

### ISSUE THREAD

**Issue by Gecked-Deck** [redromnon/HeroicBashLauncher#49]
When I ran the script all of my non-steam app icons were reset. Grids, Heros and Logos were not affected.

**Comment by redromnon** [comment]
So I've tested this and none of my existing non-steam apps' app icons have been affected. Did this happen when running the setup.sh script for the first time? I presume you're a Deck.

**Comment by Gecked-Deck** [comment]
Sorry, I realized this was user error. I deleted the folder the icons were in like a dunce, steam makes backups of Grids, Logos and Heros so they naturally weren't effected. I'll see myself out 😅

**Comment by redromnon** [comment]
Ah okay. No issues.
