### ISSUE TITLE
Unable to launch FlatPak setup script, KeyError: 'wineVersion'

### ISSUE THREAD

**Issue by gstacks13** [redromnon/HeroicBashLauncher#50]
Log attached. Let me know if you need help reproducing

[HeroicBashLauncher.log](https://github.com/redromnon/HeroicBashLauncher/files/8566724/HeroicBashLauncher.log)

**Comment by stackhousegabrielPFG** [comment]
Closing: turned out to be a Heroic config issue. Toggling Wine versions solved this issue for me.

**Comment by gstacks13** [comment]
Closing: turned out to be a Heroic config issue. Toggling Wine versions and running again solved this for me.
