### ISSUE TITLE
Game Shortcut Not Working

### ISSUE THREAD

**Issue by k-e-i-z-a-i** [redromnon/HeroicBashLauncher#51]
I ran setup.sh in the Flatpack version but when I try to run the game's sh file, I get a "Failed to launch games" error. The logs are as follows:

```
Gtk-Message: 08:48:42.212: Failed to load module "xapp-gtk3-module"
Gtk-Message: 08:48:42.212: Failed to load module "appmenu-gtk-module"
Gtk-Message: 08:48:42.246: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:48:42.246: Failed to load module "canberra-gtk-module"
3.32.0
sh: line 3: /usr/bin/gamemoderun: No such file or directory
---CANNOT CONNECT TO NETWORK. RUNNING IN OFFLINE MODE---
sh: line 3: /usr/bin/gamemoderun: No such file or directory
Gtk-Message: 08:48:42.255: Failed to load module "xapp-gtk3-module"
Gtk-Message: 08:48:42.255: Failed to load module "appmenu-gtk-module"
Gtk-Message: 08:48:42.297: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:48:42.297: Failed to load module "canberra-gtk-module"
Using Bash Launcher 2.4.2

Checking if Zenity is installed:
Launch command:
STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/xxxx/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH='/home/xxxx/Games/Heroic/Prefixes/HITMAN-3' /usr/bin/gamemoderun /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Eider --no-wine --wrapper "'/home/xxxx/.steam/steam/steamapps/common/Proton - Experimental/proton' run" 
```
I've also confirmed that:
- The Game does launch from Heroic  Games Launcher
- Steam is not running when I try to execute the game's sh file

How can I overcome this problem?

Thanks in advance for any help!

**Comment by k-e-i-z-a-i** [comment]
I have a gamemoderun file in `/usr/games`. In `/usr/bin/`, I have a gamemoded file.

I can also confirm that I have gamemode installed on my machine:

![Screen](https://user-images.githubusercontent.com/35005138/165529974-1dc16e79-1144-43f3-b8e1-95f4610d4615.png)

**Comment by k-e-i-z-a-i** [comment]
Sorry: How do I toggle off gamemode to overcome this problem?

And to just to confirm: gamemode is per-requisitefor  for HeroicBashLauncher?

**Comment by k-e-i-z-a-i** [comment]
Got it. Thank you!

**Comment by redromnon** [comment]
Issue fixed.
