### ISSUE TITLE
Setup.sh does not run - games not appearing in Steam library

### ISSUE THREAD

**Issue by Shootemup972** [redromnon/HeroicBashLauncher#52]
I have gotten Heroic Games Launcher to work successfully and can get Disco Elysium running without any issue. I would like to have my Epic/GOG games show up on Steam and I am having issues with the setup.sh script.

No message/notification if I double-click the script from the zip download. I'm not sure if I am not using Konsole correctly (not much of a PC gamer) so even if I copy it into the terminal, there is no indication the script is running.

Any thoughts on what I'm missing?

**Comment by redromnon** [comment]
There's no need to use the console. Is there a HeroicBashLauncher.log generated? You will find errors in that log.

**Comment by MrMobss** [comment]
I'm having a same issue, but a log file does generate. It says error loading python lib

**Comment by redromnon** [comment]
Can you paste the log here? Maybe that'll elaborate the issue.

**Comment by redromnon** [comment]
The current v2.6.0 version does not work on the Deck due to an older glibc library. I'll be releasing a new version soon.

**Comment by redromnon** [comment]
Is this issue solved? Should I clise this?
