### ISSUE TITLE
Not running from Steam [Bug]

### ISSUE THREAD

**Issue by SlaterDPS** [redromnon/HeroicBashLauncher#53]
I'm having an issue with bash launcher generating a script and creating a shortcut in my steam library, but not running from Steam. The game runs from the heroic launcher just fine. I'm brand new to Linux with the Steam Deck, so forgive my ignorance if i'm just missing something. 

Attached Heroic Bash Launcher log. The game launcher log folder is empty though.

[HeroicBashLauncher.log](https://github.com/redromnon/HeroicBashLauncher/files/8627732/HeroicBashLauncher.log)

**Comment by redromnon** [comment]
Did you install Heroic from the Software Store? If so, you need to download the Flatpak version of Bash Launcher.
There's a seperate log generated for each game under GameFiles/logs/ when you launch the game from Steam. You'll find errors in the Bluebird_Heroic.log.

**Comment by SlaterDPS** [comment]
Yes, i downloaded it from the Discover center. There was no bash launcher though. I found the flatpak version and used that. The game attempted to start from steam and then failed. it actually generated a log file now though. Attached. the error doesn't mean anything to me. Sorry for being dumb and thanks for the help
[Fez_Heroic.log](https://github.com/redromnon/HeroicBashLauncher/files/8628442/Fez_Heroic.log)

**Comment by SlaterDPS** [comment]
Oops, Imissed the flatseal access of the flatpak tutorial. That appears to have done the trick. Thanks so much for the help!

**Comment by redromnon** [comment]
Cool. May I request to close this issue if it's working?

**Comment by SlaterDPS** [comment]
I was hoping you could also advise on a different issue I had that probably isn’t related to The Bash Launcher.

I tried installing Celeste but the game fails to boot - however from my understanding it has to do with it not being compatible with Proton 7.0 or 6.3 (The two options in my Heroic Games Launcher). I’m told it has Native support but I don’t see an option to not use Wine through the launcher either. I’m not really sure what the best way to install and use other versions of wine in order to run games like this would be. I tried looking at Wine through the Discover center but I didn’t really know what that did.

**Comment by redromnon** [comment]
I can only discuss issues related to Bash Launcher here. Feel to ask your doubt on Heroic's Discord channel. I believe someone has got Celeste working.
