### ISSUE TITLE
[Bug] "Failed to Add Game to Steam"

### ISSUE THREAD

**Issue by macneilj** [redromnon/HeroicBashLauncher#54]
**Describe the bug**
Clicking setup.sh or HeroicBashLauncher script gives me: "Failed to add game to Steam. Please check the HeroicBashLauncher.log for the error and consider reporting it as an issue on GitHub."

**Details**

 - Platform: Steam Deck
 - Heroic Version:  v2.2.6 
 - Bash Launcher Version: v2.5.0  Flatpak

Log File:
```
Using HeroicBashLauncher Flatpak version...
3.32.0
Using Bash Launcher 2.5.0

Checking if Zenity is installed:


Done! Now creating launch files for your Epic Games library ...

Sifu [d36336f190094951873ed6138ac208d8]...



Traceback (most recent call last):
  File "steam.py", line 56, in addtosteam
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.steam/steam/userdata/0/config/shortcuts.vdf'

```

**Comment by macneilj** [comment]
Log when clicking Sifu_Heroic.log:

```
bwrap: execvp ./HeroicBashLauncher: No such file or directory
bwrap: execvp ./Downloads/HeroicBashLauncher-2.5.0_Flatpak/GameFiles/HeroicBashLauncher: No such file or directory
```

**Comment by redromnon** [comment]
Does a folder named `0` exist in `/home/deck/.steam/steam/userdata/`? If so, consider deleteing that folder and run the `setup.sh` script again.

**Comment by redromnon** [comment]
Also, go through the [Deck guide](https://github.com/redromnon/HeroicBashLauncher/wiki/Steam-Deck-(Flatpak)-Guide) to see if you missed something. I think you need to enable access in Flatseal.

**Comment by macneilj** [comment]
Deleting the "0" folder seems to have fixed this, thanks!

**Comment by redromnon** [comment]
Great! Would you mind closing the issue?

**Comment by kelvie** [comment]
For what it's worth, I also ran into this on the Steam Deck. In my case, I think game 384630 was causing this, as it only had that in there (that's Aviary Attorney).
