### ISSUE TITLE
[Bug] setup failing on SteamDeck

### ISSUE THREAD

**Issue by clemthi** [redromnon/HeroicBashLauncher#55]
**Describe the bug**
Setup is failing when starting it from Steamdeck

**To Reproduce**
1. install Heroic from Discover App and install a game
2. Get HeroicBashLauncher and unpack it
3. Execute setup.sh
4. Error window popups up:
```
Failed to add game to Steam. Please check the HeroicBashLauncher.log for the error and consider reporting it as an issue on GitHub.
```

Content of the HeroicBashLauncher.log is the following
```
Using HeroicBashLauncher Flatpak version...

(process:14846): Gtk-WARNING **: 12:36:20.115: Locale not supported by C library.
	Using the fallback 'C' locale.
3.32.0

(process:14856): Gtk-WARNING **: 12:36:24.380: Locale not supported by C library.
	Using the fallback 'C' locale.
Using Bash Launcher 2.5.0

Checking if Zenity is installed:


Done! Now creating launch files for your Epic Games library ...

Yoku's Island Express [3acb0920074446e8baaa4c249200d892]...



shortcuts.vdf already exists in 10396745
Yoku's Island Express already added to Steam.
Steam AppID for Yoku's Island Express is 3399946005
Checking Artwork...
Downloading Cover Art from https://cdn1.epicgames.com/salesEvent/salesEvent/EGS_YokusIslandExpress_VillaGorilla_S2_1200x1600-6fe8115f1b7b7107896144c8212851c4
Downloading Background Art from https://cdn1.epicgames.com/salesEvent/salesEvent/EGS_YokusIslandExpress_VillaGorilla_S3_2560x1440-8af00b59559d95cb80e7167c8fa696b7
Downloading BigPicture Art from https://cdn1.epicgames.com/salesEvent/salesEvent/EGS_YokusIslandExpress_VillaGorilla_S3_2560x1440-8af00b59559d95cb80e7167c8fa696b7



Traceback (most recent call last):
  File "steam.py", line 56, in addtosteam
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.steam/steam/userdata/0/config/shortcuts.vdf'
```

**Expected behavior**
Shortcuts should be added in Steam.

**Details**

 - Platform: SteamDeck OS 3.2 beta build 20220502.100
 - Heroic Version: v2.2.6 Flatpak
 - Bash Launcher Version: 2.5.0 Flatpack

**Comment by clemthi** [comment]
Apparently the error comes from the fact that the folder `/home/deck/.steam/steam/userdata/0/config` didn't exist. After creating it manually, the setup ran fine.

**Comment by clemthi** [comment]
I've just created a PR which should fix the issue.
https://github.com/redromnon/HeroicBashLauncher/pull/56

**Comment by redromnon** [comment]
I don't know why that `0` folder gets created. Another user faced the same thing in #54. Anyway, I've accepted your PR. Users without the `config` folder should no longer face this error.
