### ISSUE TITLE
[Bug] Steam shortcut does nothing (Steam Deck)

### ISSUE THREAD

**Issue by DreamboxMinerva** [redromnon/HeroicBashLauncher#58]
Using the setup.sh adds the games shortcut to steam correctly but then when I try to launch them there, nothing happens. :/
The games does run fine on the Heroic Games Launcher.

Here's the log files I get :

`ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
bwrap: execvp ./HeroicBashLauncher: No such file or directory
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
bwrap: execvp ./Downloads/HeroicBashLauncher-2.5.0_Flatpak/GameFiles/HeroicBashLauncher: No such file or directory`

**Comment by redromnon** [comment]
Have you enabled access to the folder path in Flatseal? Did you go through the [Deck guide](https://github.com/redromnon/HeroicBashLauncher/wiki/Steam-Deck-(Flatpak)-Guide)?

**Comment by LP0101** [comment]
Update: I fixed the issue by modifying the generated bash script.

By default, the `flatpak run` command in the script uses a relative path from `~`. ie: `./Downloads/HeroicBashLauncher/GameFiles/HeroicBashLauncher`. Once I changed that to `/home/deck/Downloads/...`, issue was resolved and game was launching fine.

**Comment by redromnon** [comment]
Maybe I should include the home directory path as well for flatpak. I'll reopen this issue and close it when I apply the fix.

**Comment by brimb8** [comment]
> 

I am having this same issue. Running the script runs fine, but when using the shortcut in Steam the game does not launch. I also am unable to find the script file in 'add non-steam game.' Can you share the exact script you changed it to?

**Comment by redromnon** [comment]
I've fixed the issue.
