### ISSUE TITLE
[Bug] Game Launcher script not regenerated if game is already added to Steam

### ISSUE THREAD

**Issue by carn1x** [redromnon/HeroicBashLauncher#66]
**To Reproduce**
1. Run setup.sh so game is added to steam
2. Delete corresponding shell script e.g. `GameFiles/SonicMania_Heroic.sh`
3. Run setup.sh again
4. Observe `GameFiles/SonicMania_Heroic.sh` still does not exist.

**Expected behavior**
Game launcher script e.g. `GameFiles/SonicMania_Heroic.sh` is regenerated after each re-run of setup.sh if the file does not exist, regardless of whether the game was already added to Steam.

**Details**

 - Platform: Steam Deck
 - OS: Steam OS
 - Bash Launcher Version: 2.6.1

**Comment by redromnon** [comment]
Can you paste the HeroicBashLauncher.log? Did you delete the GameFiles folder?

**Comment by carn1x** [comment]
I tried again by deleting the full GameFiles folder and it worked, however I had to fight with Dolphin quite a bit and found that the bug I reported is probably more due to Dolphin being very reliant on some view cache and a lack of consistent refreshing of directory listings as I found `ls` in terminal to show different but more expected results. I think this can probably be closed then sorry for the false alarm.
