### ISSUE TITLE
[Bug] Games only launch on desktop mode

### ISSUE THREAD

**Issue by SmoothDedede** [redromnon/HeroicBashLauncher#67]
**Describe the bug**
Everything works perfectly, games are added to my library and launch fine. However i cant open them on the steam "game mode" only on desktop mode.

**To Reproduce**
1. Do the usual steps (installing game, running setup script etc.)
2. When the games are added to your steam library run them in desktop mode, this should work.
3. Switch over to game mode
4. run the game again, now it should load and then take you back to the home screen.

 - Platform: [Steam Deck]
 - OS: [default steam deck os]
 - Heroic Version: [newest version]
 - Bash Launcher Version: [v2.6.1 Base]

**Additional info**
I had this problem with FFVII Remake

**Comment by redromnon** [comment]
Is it just with FFVII Remake or all games as you mentioned? 
Please check the game's log under `HeroicBashLauncher/GameFiles/logs/` for the errors.

**Comment by SmoothDedede** [comment]
Hi i read through some old reports and got it working, i added exec > log.log 2>&1 to the code and launched it from proton ge instead of wine in heroic.
Thanks the software haha it's truely awesome!
