### ISSUE TITLE
Gamemode Preventing Launch

### ISSUE THREAD

**Issue by k-e-i-z-a-i** [redromnon/HeroicBashLauncher#68]
Hi,

The Gamemode problem hasn't been fixed yet by the changes made in 2.6.1:

```
3.32.0
Using Bash Launcher 2.6.1

Checking if Zenity is installed:
./launchflatpakgame.sh: line 10: /home/XXXX/Games/HeroicBashLauncher/GameFiles/binaries/legendary: No such file or directory
./launchflatpakgame.sh: line 12: /usr/games/gamemoderun: No such file or directory
---CANNOT CONNECT TO NETWORK. RUNNING IN OFFLINE MODE---
./launchflatpakgame.sh: line 12: /usr/games/gamemoderun: No such file or directory
Gtk-Message: 08:20:11.762: Failed to load module "xapp-gtk3-module"
Gtk-Message: 08:20:11.762: Failed to load module "appmenu-gtk-module"
Gtk-Message: 08:20:11.795: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:20:11.795: Failed to load module "canberra-gtk-module"
```
I get a "Failed to launch" error.  The game does successfully launch from Heroic Games Launcher.

**Comment by redromnon** [comment]
That's odd. HBL tries to find gamemoderun's location that can be either located in `/usr/bin/gamemoderun` or `/usr/games/gamemoderun`.
Are you sure gamemode is installed on your system? You can check it by running `which gamemoderun` in the terminal.

**Comment by k-e-i-z-a-i** [comment]
`which gamemoderun` produces `/usr/games/gamemoderun`.

I'm certain gamemode is installed on my system:

![165529974-1dc16e79-1144-43f3-b8e1-95f4610d4615](https://user-images.githubusercontent.com/35005138/169700619-ba2b55b4-a7b3-463c-a06f-35b2f868a0cb.png)

**Comment by redromnon** [comment]
So is mine. I have no idea why it isn't working on your system.

**Comment by redromnon** [comment]
Is this issue solved? Does enabling gamemoderun work for you now?

**Comment by k-e-i-z-a-i** [comment]
> Is this issue solved? Does enabling gamemoderun work for you now?

No, it still doesn't work for me.

**Comment by redromnon** [comment]
Okay, can you try toggling off gamemode and type `gamemoderun` in the Advanced Options section of a game?

**Comment by k-e-i-z-a-i** [comment]
> Okay, can you try toggling off gamemode and type `gamemoderun` in the Advanced Options section of a game?

Yes, this worked. Typing 'gamemoderun' in the Advanced Options section of a game will allow the game to run, while having gamemode toggled will not.

**Comment by redromnon** [comment]
That's a workaround for now. Did you also try the latest v2.7.2? I've just used `gamemoderun` as the parameter that is similar to the above workaround.

**Comment by k-e-i-z-a-i** [comment]
> That's a workaround for now. Did you also try the latest v2.7.2? I've just used `gamemoderun` as the parameter that is similar to the above workaround.

Sorry, I've discontinued use of HeroicBashLauncher, so I'm no longer able to investigate.

**Comment by redromnon** [comment]
No problem. I'll close this issue then.
