### ISSUE TITLE
[Feature Request] Option to disable automatic image fetching

### ISSUE THREAD

**Issue by outphase** [redromnon/HeroicBashLauncher#72]
Right now, HBL obtains images according to the .json files. However, they are for EGS and not properly sized to the various Steam UI image dimensions, or they are not centered properly. For example, the same image is used for the landscape grid banner and the hero image, so portions of the image are cropped differently.

I would like to have an option to prevent HBL from retrieving images as indicated in the .json.

**Comment by redromnon** [comment]
The issue has been fixed in v2.8.0
