### ISSUE TITLE
Running Script gives an Error (wineVersion) [Bug]

### ISSUE THREAD

**Issue by lxlumen** [redromnon/HeroicBashLauncher#75]
### Before posting this issue, make sure you've read the [Issues section in the Readme](https://github.com/redromnon/HeroicBashLauncher#issues-and-suggestions) and the [Flatpak/Steam-Deck guide](https://github.com/redromnon/HeroicBashLauncher/wiki/Steam-Deck-(Flatpak)-Guide).

**Describe the bug**
Running the HeroicBash Launcher or setup.sh gives the following error: 
Process Failed

Please check the game log under GameFiles/logs/ in the HeroicBashLauncher folder for the error and consider reporting it as an issue on GitHub.

The Log says:

3.32.0
Using Bash Launcher 2.7.2

Checking if Zenity is installed:

Done! Now creating launch files for your Epic Games library ...

Inside [Marigold]...
Traceback (most recent call last):
  File "func/checkparameters.py", line 261, in checkparameters
KeyError: 'wineVersion'

**To Reproduce**
1. Follow the Flatpak Guide
2.  try running the setup.sh script
3. error

**Expected behavior**
Generation of game specific scripts to add to steam

**Details**

 - Platform: Steam Deck
 - OS: SteamOS 3.2
 - Heroic Version: 2.3.4 Flatpack
 - Bash Launcher Version: 2.7.2

**Additional context**
Running on Steam Deck with latest software. Running games in Heroic works.
Thank you for your work!

**Comment by redromnon** [comment]
Heroic saves your game's settings to the game's json file (which Bash Launcher reads) once you launch the game. Then try running the `setup.sh` script. 
Do the same for any newly installed game.

**Comment by lxlumen** [comment]
That doesn't work unfortunately. 
The log says this:


3.32.0

** (zenity:21517): WARNING **: 09:33:57.634: AT-SPI: Could not obtain desktop path or name


** (zenity:21517): WARNING **: 09:33:57.655: AT-SPI: Could not obtain desktop path or name


** (zenity:21517): WARNING **: 09:33:57.656: atk-bridge: get_device_events_reply: unknown signature

** (zenity:21517): WARNING **: 09:33:57.656: atk-bridge: get_device_events_reply: unknown signature

** (zenity:21517): WARNING **: 09:33:57.656: atk-bridge: GetRegisteredEvents returned message with unknown signature

** (zenity:21517): WARNING **: 09:33:57.670: AT-SPI: Could not obtain desktop path or name


** (zenity:21517): WARNING **: 09:33:57.670: atk-bridge: get_device_events_reply: unknown signature

** (zenity:21517): WARNING **: 09:33:57.670: atk-bridge: get_device_events_reply: unknown signature

** (zenity:21517): WARNING **: 09:33:57.670: atk-bridge: GetRegisteredEvents returned message with unknown signature

** (zenity:21546): WARNING **: 09:34:00.184: AT-SPI: Could not obtain desktop path or name


** (zenity:21546): WARNING **: 09:34:00.199: AT-SPI: Could not obtain desktop path or name


** (zenity:21546): WARNING **: 09:34:00.199: atk-bridge: get_device_events_reply: unknown signature

** (zenity:21546): WARNING **: 09:34:00.199: atk-bridge: get_device_events_reply: unknown signature

** (zenity:21546): WARNING **: 09:34:00.199: atk-bridge: GetRegisteredEvents returned message with unknown signature

** (zenity:21546): WARNING **: 09:34:00.213: AT-SPI: Could not obtain desktop path or name


** (zenity:21546): WARNING **: 09:34:00.213: atk-bridge: get_device_events_reply: unknown signature

** (zenity:21546): WARNING **: 09:34:00.214: atk-bridge: get_device_events_reply: unknown signature

** (zenity:21546): WARNING **: 09:34:00.214: atk-bridge: GetRegisteredEvents returned message with unknown signature
Using Bash Launcher 2.7.2

Checking if Zenity is installed:


Done! Now creating launch files for your Epic Games library ...

Alien: Isolation [8935bb3e1420443a9789fe01758039a5]...



shortcuts.vdf already exists in 99001794
Adding Alien: Isolation to Steam
Steam AppID for Alien: Isolation is 2183203676
Created grid folder in  /home/deck/.steam/steam/userdata/99001794/config/grid
Checking Artwork...
Downloading Cover Art from https://cdn1.epicgames.com/df37f065c3f14eadbf011177396e2966/item/EGS_AlienIsolation_CreativeAssembly_S6-1200x1600-af00adc8f67a7c6138cce183ac1e9503.jpg
Downloading Background Art from https://cdn1.epicgames.com/df37f065c3f14eadbf011177396e2966/item/EGS_AlienIsolation_CreativeAssembly_S5-1920x1080-1cf3b9a86adcefeebf903451b1b3fb49.jpg
Downloading BigPicture Art from https://cdn1.epicgames.com/df37f065c3f14eadbf011177396e2966/item/EGS_AlienIsolation_CreativeAssembly_S5-1920x1080-1cf3b9a86adcefeebf903451b1b3fb49.jpg
Inside [Marigold]...
Traceback (most recent call last):
  File "func/checkparameters.py", line 261, in checkparameters
KeyError: 'wineVersion'

**Comment by ligerzero459** [comment]
> Did you set the wine version in the game's settings and launch Inside from Heroic?

Can confirm that this works. I had to change the Wine version in the game settings to get it to actually save, then launched the game. Afterwards the error disappeared

**Comment by redromnon** [comment]
You can test the [latest build](https://github.com/redromnon/HeroicBashLauncher/actions/runs/2474115884) that solves this issue without the user needing to change the wine version manually. 
Make sure to try this on 
a) Newly installed games only without chnaging any settings OR
b) By deleting the game's json file in `/heroic/GamesConfig/` and restarting Heroic.

**Comment by redromnon** [comment]
The bug should be fixed in the latest v2.7.3 release. Do note that the user should have opened the Global Settings atleast once in the past so that the json file gets updated with the default wine version.
