### ISSUE TITLE
Games not starting on Steamdeck

### ISSUE THREAD

**Issue by Pixelplanet** [redromnon/HeroicBashLauncher#77]
Ive followed the guide and everything works fine until you try to launch a game.
It briefly does something and then returns to the gamemode UI without doing anything or displaying any error message.

launching the .sh file of a game manually also does nothing at all and shows no error messages.

ive tried both CIV 6 and Control both launch without any problems in the heroic launcher itself, its just the short cuts being added to steam that dont do anything.

Is there any step missing in the guide on here?

Downloaded and started heroic
Downloaded and started games without any problems
Downloaded and selected the latest legendary file
Downloaded Heroicbashlauncher
Set heroic launcher in flatseal to be able to access all user files.
Finally ran the heroicbash script and got the confirmation message that it has done its thing.
return to game mode, the games are there as expected but nothing can be launched.

**Comment by redromnon** [comment]
You don't need to download legendary anymore.

Try looking for errors in the game's log files situated in `GameFiles/logs/`

**Comment by Pixelplanet** [comment]
heres the log file that is generated.
i also tried without downloading legendary and same result.

[SidMeiersCivilizationVI_Heroic.log](https://github.com/redromnon/HeroicBashLauncher/files/8834076/SidMeiersCivilizationVI_Heroic.log)

**Comment by redromnon** [comment]
It's not able to find the prefix when launched from HBL. Maybe try deleting the prefix and see if Heroic creates a new one. Then launch from the sh file.

**Comment by redromnon** [comment]
Is your prefix located in the `Games/Heroic` directory?

**Comment by Pixelplanet** [comment]
the prefix is located in the default folder where herioc launcher puts them /home/deck/.wine
i can also find one folder with a prefix in home/games/heroic/_gamename_ but only for Control and not for CIV but control also doesnt launch.

the difference here is Control was installed using Proton 6.8 something while CIV was installed using ProtonGE 7.20 so i guess that puts the prefix into a different folder
After searching a bit i the folder /Home/.steam/steam/compatibilitytools.d/GE-Proton7-20/Protonfixes
but that doesnt seem to have anything useful in there.

the game folder itself has no prefix in there but launches just fine using heroic launcher itself.
no idea whats going on here, everything was left on its default settings with the one exception of installing CIV with proton GE because it doesnt launch if its installed with regular proton.

**Comment by redromnon** [comment]
It's better to have separate prefixes for every games and not in the default `~/.wine`. 
It's usually placed in `/Games/Heroic/Prefixes/GameName`

**Comment by Pixelplanet** [comment]
i just uninstalled every game, heroic launcher and heroic bash and redownloaded everything.
this time it worked fine so i guess this has something to do with downloading protonGE after already having heroic launcher installed.

No idea why exactly this happened but it seems to be fixed now, thanks for the help.
