### ISSUE TITLE
[Bug] HBL Modifies shortcuts.vdf incorrectly

### ISSUE THREAD

**Issue by cbartondock** [redromnon/HeroicBashLauncher#78]
### Before posting this issue, make sure you've read the [Issues section in the Readme](https://github.com/redromnon/HeroicBashLauncher#issues-and-suggestions) and the [Flatpak/Steam-Deck guide](https://github.com/redromnon/HeroicBashLauncher/wiki/Steam-Deck-(Flatpak)-Guide).

**Describe the bug**
I'm the dev for Steam ROM Manager. I've noticed that several users that also use HBL are experiencing bugs in SRM. 

The reason is the way that the steam file `shortcuts.vdf` gets modified by HBL. The structure of `shortcuts.vdf` (once converted to a JSON) should be 
```json
{
  "shortcuts": [
    0: {...}, //app1
    ...
  ]
}
```
But instead it's 
```json
{
  "shortcuts": {
    "": {...}
  }
}
```
Since SRM expects an array under "shortcuts", it breaks when trying to push things to it. Perhaps HBL is handling this incorrectly when the user is only adding a single game to Steam?

**To Reproduce**
Not sure because I don't use HBL. But basically, add (maybe just one) game to steam with HBL then try to use SRM (or other similar tools).

**Expected behavior**
Shortcuts.vdf readable and writeable by SRM after being modified by HBL.

**Screenshots**
Here is the jsonified version of a shortcuts.vdf file that has been modified by HBL, as seen in SRM: 
![Screenshot_20220607_161242](https://user-images.githubusercontent.com/4482454/172478420-cfc9336e-ebb4-45e0-876a-79c3cba124f1.png)

**Details**

 - Platform: Any
 - OS: Any
 - Heroic Version: Not sure
 - Bash Launcher Version: Not sure

**Comment by cbartondock** [comment]
Here's another photo where the difference between manually/SRM added shortcuts (top) and HBL added shortcuts (bottom) is more apparent:
![Screenshot_20220607_183518](https://user-images.githubusercontent.com/4482454/172494686-e9ea5123-89b9-4aac-abb1-163a4f884bd9.png)
.

**Comment by Nocccer** [comment]
Maybe we use all the same library. Saw that this is available in python and node:
https://github.com/Lagg/steamodd/

Maybe there is another better library

**Comment by cbartondock** [comment]
That's not a bad idea. SRM currently uses https://github.com/node-steam/vdf, don't think there is a python equivalent. But really as long as that library parses and vdfifies correctly, it should work.

**Comment by Nocccer** [comment]
Found the python library through this node library:
https://github.com/rjackson/node-vdf

They say it is a rewrite of it in node.

**Comment by cbartondock** [comment]
Oh nice that's perfect then.

**Comment by Nocccer** [comment]
So actually does not matter which library, but we need to use one. Thanks for this tipp.

**Comment by redromnon** [comment]
I feel it'll be better to use the Python library that @Nocccer found since it parses the vdf similar to the one used by SRM.
I haven't dug deep into it since I'm currently busy.

**Comment by Nocccer** [comment]
You just need the vdf serializer.

**Comment by Nocccer** [comment]
@cbartondock actually i'm confused that you use less entries for each game. I thought you need to declare all of the possible entries:
https://github.com/CorporalQuesadilla/Steam-Shortcut-Manager/wiki/Steam-Shortcuts-Documentation#shortcut-entry-structure

**Comment by cbartondock** [comment]
No I don't think you do - steam is clever enough to just ignore ones that aren't set. - For the sake of Accuracy™ it would probably be best to do so, but as far as I know it causes no issues to set only the ones SRM sets.

**Comment by Nocccer** [comment]
Actually i try the vdf node library you use and it does not work for writing ? It writes plain json into vdf file ?
From my understanding `writeFileSync(shortcutsFile, stringify({ shortcuts: {} }))` should do resolve to `shortcuts` in shortcuts.vdf and not to `shortcuts: {}`

**Comment by cbartondock** [comment]
Whoops! That's because that's the wrong library I gave you. Refer to https://github.com/SteamGridDB/steam-rom-manager/blob/master/src/lib/vdf-shortcuts-file.ts

What we are using is [steam-shortcuts-editor](https://github.com/tirish/steam-shortcut-editor).

Sorry for the bad steer!

**Comment by Nocccer** [comment]
Ok thanks so i will see if there is a python library for that aswell

**Comment by Nocccer** [comment]
@redromnon maybe this works ?

https://pypi.org/project/steamclient/

**Comment by cbartondock** [comment]
It looks right to me! If you want to send me a shortcuts.vdf that has been created /edited by it I can test to see if it has the correct structure when converted to json

**Comment by redromnon** [comment]
> @redromnon maybe this works ?
> 
> https://pypi.org/project/steamclient/

This should do it. Thanks a lot @Nocccer for this!

**Comment by cbartondock** [comment]
When you fix this be sure to have some mechanism in place to deal with already corrupted files, otherwise you will most likely see the same errors as SRM due to the fact that an array of shortcuts is expected by the library.

**Comment by Nocccer** [comment]
Maybe there is a why we could test if a created shortcuts.vdf is not corrupted after changes and if so we could bring up the old shortcuts.vdf

**Comment by Nocccer** [comment]
But actually there is no way without starting steam

**Comment by cbartondock** [comment]
No there is. Check if the field shortcuts exists and if it is an array. If it is an object migrate things over to the array format.

**Comment by cbartondock** [comment]
Ah but your library doesn't output a JSON? Just specific entries etc?

**Comment by Nocccer** [comment]
For me i can use your check. But sometimes you miss something and your check pass but steam complains about shortcuts.vdf. Would be good to have something to see if steam can read it.

**Comment by cbartondock** [comment]
Yeah I mean unless you want to run the steam executable and somehow record if it has an error (no idea how you would do that) the best you can do is try to guarantee the file conforms to your expectations - if steam changes things on their end (which they usually don't but obviously could) then it will break and we'll have to fix it. 

That's the game of cat and mouse dozennn and I have been playing for years now lol.

**Comment by redromnon** [comment]
@Nocccer Unfortunately https://pypi.org/project/steamclient/ doesn't work because it needs winreg (Windows Registry Access) that is not available on Linux.

**Comment by Nocccer** [comment]
@redromnon you can use the class from the project and write a function were you can pass the filepath. I looked over the source code and it looked pretty easy todo

**Comment by redromnon** [comment]
Okay, thanks. I'll look into that. How about this - https://github.com/CorporalQuesadilla/Steam-Shortcut-Manager? A bit older but simple.

**Comment by Nocccer** [comment]
Also possible. What fits better for you.

**Comment by Nocccer** [comment]
@cbartondock can you test for me this shortcuts.vdf. I created it manually with steam. It seems the steam-shortcut-editor does not create correct json.
[shortcuts.zip](https://github.com/redromnon/HeroicBashLauncher/files/8881316/shortcuts.zip)

**Comment by Nocccer** [comment]
Weird. The appid is different than mine. So probably something on my end.

**Comment by redromnon** [comment]
@cbartondock I have a theory. Does SRM expect the srno and the appid in the vdf when converting into json format? HBL currently doesn't include those two and this may be the issue.

I'll try to fix this. Otherwise I will have to make use of the project I last mentioned.

**Comment by cbartondock** [comment]
SRM puts the app id in there for the sake of accuracy and I think because very rarely steam uses it, but no it doesn't depend on it already being there. We compute the app id directly from the location of the executable and the title name.

The main thing that is causing an error in SRM is the fact that it expects an array under shortcuts.

**Comment by redromnon** [comment]
I've noticed that once HBL adds the games to `shortcuts.vdf`, the user needs to manually add another shortcut so that Steam corrects the syntax and then probably move forward to use SRM. Obviously this is an inconvenient workaround.

**Comment by Nocccer** [comment]
Found this library for reading vdf in python.
https://github.com/ValvePython/vdf

**Comment by redromnon** [comment]
I had already come across this library but it is not used to read `shortcuts.vdf`. It is intended to be used for devs for the KeyValue format. I tried but it doesn't work and gives UnicodeDecode Error.

**Comment by redromnon** [comment]
I'm currently working on (close to) fixing this issue in HBL itself rather than depending on a library.

**Comment by Nocccer** [comment]
Found something interesting. If you manually adapt the AppName directly in shortcuts.vdf and a appid is defined. The parser will fail somehow with the error i had above.

**Comment by redromnon** [comment]
> I would suggest the library. If i'm done in heroic i can copy and rewrite it in python.
> 
> @redromnon Looks good here: https://replit.com/@Nocccer/SteamShortcut#main.py

Great! Looks like there'll be no further problems with SRM and even the function you are working on for Heroic.
I don't have to depend on any library anymore. I just to had carefully revise the format given by Valve here -  https://developer.valvesoftware.com/wiki/Add_Non-Steam_Game

**Comment by redromnon** [comment]
For further testing, [this workflow build](https://github.com/redromnon/HeroicBashLauncher/actions/runs/2492648615) can be used to test HBL with the fix.

**Comment by cbartondock** [comment]
Sorry I was travelling, but great work. Shall I close the issue here and over at SRM?

**Comment by redromnon** [comment]
No issues. Yeah, you can close it.
