### ISSUE TITLE
Error while running games under Proton

### ISSUE THREAD

**Issue by auron95** [redromnon/HeroicBashLauncher#8]
After launching the bash file for the game "Brothers - A Tale of Two Sons", using Proton 7.0, a message would appear, complaining that "The map specified by the commandline 'wine' could not be found". After some testing, it looks like there's a typo [here](https://github.com/redromnon/HeroicBashLauncher/blob/102b260454b455b65eff6da4e5f1d42511aa025e/func/checkparameters.py#L206), since changing "--no wine" into "--no-wine" in the .sh file solved the issue (I guess it was recognizing wine as a command and not as an argument).

**Comment by redromnon** [comment]
Yeah, that's indeed a typo. I'll make the change soon. Thanks for letting me know!

**Comment by redromnon** [comment]
Fixed the typo. Closing the issue.
