### ISSUE TITLE
[Bug] Selecting an alternative EXE in HBL that contains spaces generates an invalid launcher script due to unquoted parameter.

### ISSUE THREAD

**Issue by nicktobey** [redromnon/HeroicBashLauncher#80]
**Describe the bug**

**To Reproduce**
(My steps were with Kingdom Hearts 1.5+2.5, but I imagine any game should work, this is just the one that happens to use spaces in the file name and has a legitimate reason for replacing the EXE)
1. Go to HGL -> KINGDOM HEARTS HD 1.5+2.5 REMIX -> Settings -> Other
2. Click "Select EXE" and choose "Heroic/KH_1.5_2.5/KINGDOM HEARTS II FINAL MIX.exe" in the file picker
3. Run HBL's setup.sh
4. Try to run the produced ./KINGDOMHEARTSHD1525ReMIX_Heroic.sh

**Expected behavior**
The game launces directly into KH2, skipping the initial game select launcher.

**Actual behavior**
Fails to launch with error:

ValueError: Executable path is invalid: /home/deck/Games/Heroic/KH_1.5_2.5/KINGDOM

**Details**

 - Platform: Steam Deck
 - OS: Steam OS
 - Heroic Version: v2.3.7
 -  - Bash Launcher Version: v2.7.1 Base

**Additional context**
The generated launchflatpakgame.sh reveals the cause (I've attached it):

--override-exe /home/deck/Games/Heroic/KH_1.5_2.5/KINGDOM HEARTS II FINAL MIX.exe

Because this parameter is not quoted, bash splits the parameter after KINGDOM. The filename should be quoted so that the whole thing is passed in as a parameter.
[launchflatpakgame.txt](https://github.com/redromnon/HeroicBashLauncher/files/8883403/launchflatpakgame.txt)

**Comment by redromnon** [comment]
Can you please test this [workflow build](https://github.com/redromnon/HeroicBashLauncher/actions/runs/2479573063) and let me know if it works? 
Just replace the executable with the existing one and run setup.sh

**Comment by nicktobey** [comment]
I was able to launch the game with the generated script.
