### ISSUE TITLE
[Bug] Games launch twice from Steam (Desktop & Deck Game Mode UI)

### ISSUE THREAD

**Issue by redromnon** [redromnon/HeroicBashLauncher#81]
### Before posting this issue, make sure you've read the [Issues section in the Readme](https://github.com/redromnon/HeroicBashLauncher#issues-and-suggestions) and the [Flatpak/Steam-Deck guide](https://github.com/redromnon/HeroicBashLauncher/wiki/Steam-Deck-(Flatpak)-Guide).

**Describe the bug**
Some users are complaning about games added by Bash Launcher launching for a second time when closed. This is only happening when launching games from Steam Desktop and Steam Deck Game Mode UI. 
Moreover, the game log under `GameFiles/logs/` maybe corrupted and will fail to open using a text editor.
Lastly, I'm not sure of this issue only occurs with the Deck.

**To Reproduce**
1. Open Steam Desktop/ Deck GameMode UI
2. Select a game
3. Click on Play
4. Wait for game to launch and attempt to exit the game
5. See second instance of game

**Expected behavior**
The second instance of the game shoudn't be created.

**Screenshots**
None

**Details**

 - Platform: Any
 - OS: Any
 - Heroic Version: v2.3.4
 - Bash Launcher Version: v2.7.2

**Additional context**
User reports indicate this issue mostly occurs with GOG games. Please check for Epic games too.

**Comment by Ishindri** [comment]
Reopening this per discussion on Discord. I'm seeing this issue with the GOG version of Pathfinder: Wrath of the Righteous, running on Steam Deck. When launching from the Game Mode UI, after quitting it starts back up again. Quitting the second instance gives me the 'failed to launch' dialog.

- Platform: Steam Deck
- OS: SteamOS
- Heroic Version: v2.3.10
- Bash Launcher Version: v2.8.1

This is a fresh log, generated from a single test of hitting Play and quitting all the resulting instances.

[PathfinderWrathoftheRighteous_Heroic.log](https://github.com/redromnon/HeroicBashLauncher/files/9175120/PathfinderWrathoftheRighteous_Heroic.log)

Let me know if I can gather additional info or do tests!

**Comment by redromnon** [comment]
I can confirm the game is launching twice - online and offline mode - based on the script. Usually, the script uses the offline mode if a game fails to start in the online mode if internet connectivity is required. 

Can I assume that the game is well playable on both instances? Like it doesn't quit abruptly?
Also, do you face such issues with other GOG games (Linux native included) and Epic games if installed any?

**Comment by Ishindri** [comment]
Both instances of the game seem stable and playable as far as I've tested.
No crashes or abnormal performance issues.

So far, this is the only game I've had the issue occur on. I've played a
number of GOG and Epic games through the Gamemode UI, and none of the
others exhibit this issue.

**Comment by redromnon** [comment]
Can you test this build? - https://github.com/redromnon/HeroicBashLauncher/actions/runs/2753975197
Just download the executable and replace it with the current one.

**Comment by Ishindri** [comment]
Tested with the new executable - I can confirm that the game is only launching once now. Oddly, upon quitting, I'm still getting an error popup saying that the game couldn't be launched. Latest logs attached.

[PathfinderWrathoftheRighteous_Heroic.log](https://github.com/redromnon/HeroicBashLauncher/files/9214757/PathfinderWrathoftheRighteous_Heroic.log)

**Comment by redromnon** [comment]
Technically, the error popup gets displayed if the launch command fails. So maybe when you quit the game, it is resulting in a "False" state and executing that error popup.
How are you quitting the game - using the in-game option or via Deck's overlay?

**Comment by Ishindri** [comment]
Just tested - the popup occurs in the same fashion regardless of whether I quit via the exit option ingame or the Deck overlay.

**Comment by redromnon** [comment]
Is this issue still present while using the latest v2.9.1? As an alternative, you can use Heroic's add-to-steam feature for that particular game.
