### ISSUE TITLE
[Bug] error: wineVersion

### ISSUE THREAD

**Issue by qube-03** [redromnon/HeroicBashLauncher#82]
**Describe the bug**
When running setup.sh, it tells me that 

**To Reproduce**
1. install games in heroic and use a custom wine version in lutris (wine tkg/proton ge)
2. run setup.sh to get the shell scripts so i can figure out how to put them into lutris
4. error wineVersion

**Expected behavior**
get the shell scripts for the games

**Screenshots**

**Details**

 - Platform: Desktop
 - OS: Artix Linux, zen kernel
 - Heroic Version: 2.3.7 normal package
 - Bash Launcher Version: tried both most recent ones

**Additional context**
i dont know where to run this script so maybe thats the error, do i run it in the games directory, the directory where i downloaded it or where else? i am aware that an issue similar to this exists, but it didnt help much. thanks in advance

**Comment by redromnon** [comment]
Are you talking about #75? Do you get the same error?

**Comment by qube-03** [comment]
yes its similar, but i couldnt figure out how to fix my issue with that one

**Comment by redromnon** [comment]
Try downloading the workflow build from link mentioned in that issue.

**Comment by qube-03** [comment]
ill try that, but i just dont know where to run the ./setup script

**Comment by qube-03** [comment]
now my problem is where to put this new script in lutris but ill read and see if i find anything

**Comment by qube-03** [comment]
found it out and it worked, rtfm lol, closing this now
