### ISSUE TITLE
[Bug] GLIBC_2.35 not found

### ISSUE THREAD

**Issue by PoL0** [redromnon/HeroicBashLauncher#84]
### Before posting this issue, make sure you've read the [Issues section in the Readme](https://github.com/redromnon/HeroicBashLauncher#issues-and-suggestions) and the [Flatpak/Steam-Deck guide](https://github.com/redromnon/HeroicBashLauncher/wiki/Steam-Deck-(Flatpak)-Guide).

**Describe the bug**
When running HeroicBashLauncher I get the following .log:
[627258] Error loading Python lib '/tmp/_MEIBtOunM/libpython3.10.so.1.0': dlopen: /usr/lib/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIBtOunM/libpython3.10.so.1.0)

**To Reproduce**
1. Open shell and navigate to HeroicBashLauncher directory
2. Run HeroicBashLauncher
3. It fails silently.

**Details**

 - Platform: Steam Deck
 - OS: SteamOS.
 - Heroic Version: 2.3.9 Flatpack (installed from Discover)
 - Bash Launcher Version: v2.7.4 Base

**Additional context**
- SteamDeck on OS Beta channel.
- Steam on Steam Deck beta channel. 
- Fully updated to latest SteamOS (3.2) / Steam (1655949179)

GLibc 2.31+ installed:
$ pacman -Q glibc
glibc 2.33-5

**Comment by redromnon** [comment]
Oh yeah, I forgot to used the workflow build binary. My bad.

**Comment by redromnon** [comment]
I've reuploaded the zip files with the correct binaries. Please check if it works.

**Comment by PoL0** [comment]
That was quick! Tested and working on SteamDeck.

Thanks a ton @redromnon <3
