### ISSUE TITLE
Change default launch language

### ISSUE THREAD

**Issue by MrArdillo** [redromnon/HeroicBashLauncher#87]
I want to play all my games on Spanish but i don't want to change it for every script so if i can put the language the first time the program launches

**Comment by redromnon** [comment]
I know there's a new feature in Heroic Beta that let's you specify the language for the game. I can use that for the scripts.

**Comment by redromnon** [comment]
Are you changing this line for Spanish? 
`export LC_ALL=en_US.UTF-8`

**Comment by MrArdillo** [comment]
Yes, but with that changed all come as en_US anyway and I need to change the line game per game

**Comment by redromnon** [comment]
Yeah, that's because HBL updates the script everytime you launch the game to check for any change in Heroic's settings. I'll work on this one.

**Comment by redromnon** [comment]
Can you try this build - https://github.com/redromnon/HeroicBashLauncher/actions/runs/2616490175 - and let me know if it works?
You will need Heroic 2.4.0 Beta for this and enter the two-letter language code in the game's Other settings under Preferred Language like `es` in your case.

**Comment by MrArdillo** [comment]
It seems to work but the problem is the same if i need to add the parameter for all the games one by one

**Comment by redromnon** [comment]
Yes. I don't see any global setting for that in Heroic. But it's a one-time step though.

**Comment by MrArdillo** [comment]
So after doing that all my scripts will execute the games in that language?

**Comment by redromnon** [comment]
I don't know, I haven't tested it thoroughly since I use English as my system local language.

**Comment by MrArdillo** [comment]
I'll try later batman arkham asylum and we'll see if it works

**Comment by redromnon** [comment]
Did you get it to work?

**Comment by redromnon** [comment]
Ok, so you don't need to specify the language setting for each game. HBL will now use the default language you've set for Heroic.

**Comment by redromnon** [comment]
Feature implemented in v2.8.0
