### ISSUE TITLE
[Bug] Install script exits saying that it isn't in `~/Games/Heroic` when it is.

### ISSUE THREAD

**Issue by javalsai** [redromnon/HeroicBashLauncher#90]
### I've read the [Issues section in the Readme](https://github.com/redromnon/HeroicBashLauncher#issues-and-suggestions) and the [Flatpak/Steam-Deck guide](https://github.com/redromnon/HeroicBashLauncher/wiki/Steam-Deck-(Flatpak)-Guide).

**Describe the bug**
Install script exits saying that it isn't in `~/Games/Heroic` when it is.

**To Reproduce**
(First Screenshot)

**Expected behavior**
Begin installation

**Screenshots**
![image](https://user-images.githubusercontent.com/80113062/179382843-0031c11d-e375-4b70-b789-bba43bd50ccc.png)
![image](https://user-images.githubusercontent.com/80113062/179383050-46b671c6-2742-4dc5-ad6e-985e99600efc.png)

**Details**

 - Platform: Desktop
 - OS: Arch
 - Heroic Version: heroic-games-launcher-bin 2.3.9-2 (from AUR)
 - Bash Launcher Version: v2.8.0

**Additional context**
I have my heroic directory placed in `/opt/games/heroic/javalsai`, but I tried two things:
 * Creating a symlink (`~/Games/Heroic -> /opt/games/heroic/javalsai`) 
 * Creating and empty directory in `~/Games/Heroic`

Both failed with the same error (in the screenshot I tried symlink method).

**Comment by redromnon** [comment]
Strange. HBL checks if the `Games/Heroic/` path exists in the current directory (basically `/home/username/Games/Heroic/HeroicBashLauncher`) before proceeding and your case satisfies the condition.

**Comment by redromnon** [comment]
Can you directly click/run the HeroicBashLauncher executable via GUI?

**Comment by javalsai** [comment]
### Thanks for the reply!!!
> Can you directly click/run the HeroicBashLauncher executable via GUI?

It just fails showing a window with the second screenshot.

**Comment by javalsai** [comment]
I tried with the version 2.7.5 and it tells me that there is a newer version, that should mean that there passed the directory check, right???

**Comment by redromnon** [comment]
Yes, because there was no directory check implemented in that release.

**Comment by javalsai** [comment]
I found the problem.
In this line:
https://github.com/redromnon/HeroicBashLauncher/blob/1a923c99c0aa30a020b299c4a91bef8942003611/func/HeroicBashLauncher.py#L18
`os.getcwd()` doesn't return the user home directory, instead it returns the current directory, which in my case is  `~/Games/Heroic/HeroicBashLauncher`, this can be seen very easily in a python repl:
![image](https://user-images.githubusercontent.com/80113062/179395632-31e63940-17a6-4b13-bfb6-33a0d298f2fb.png)

**Comment by redromnon** [comment]
Ah, that's because you have created a symlink if I'm not wrong.

**Comment by javalsai** [comment]
I think that it should be replaced with `os.path.expanduser('~')`

**Comment by redromnon** [comment]
Here's mine
![Screenshot from 2022-07-17 16-51-37](https://user-images.githubusercontent.com/74495920/179395761-914e56ad-96c1-4948-8a40-c5a2d69920bc.png)

**Comment by redromnon** [comment]
> I think that it should be replaced with `os.path.expanduser('~')`

It returns `/home/username`. It should be part of `os.getcwd()` path.

**Comment by javalsai** [comment]
> Here's mine ![Screenshot from 2022-07-17 16-51-37](https://user-images.githubusercontent.com/74495920/179395761-914e56ad-96c1-4948-8a40-c5a2d69920bc.png)

The script checks if there is a directory called `Games/Heroic` placed in `os.getcwd` (in your case it would be `/home/redromnon/Games/Heroic/HeroicBashLauncher`), but because `/home/redromnon/Games/Heroic/HeroicBashLauncher/Games/Heroic` does not exist it should fail

**Comment by redromnon** [comment]
Yes, the second path does not and should not exist.

**Comment by redromnon** [comment]
Since in my case `os.getcwd` returns `/home/redromnon/Games/Heroic/HeroicBashLauncher`, HBL checks if `/Games/Heroic/` is present in that path, which it is.

**Comment by redromnon** [comment]
I think that symlink is causing the issue.

**Comment by javalsai** [comment]
> I think that symlink is causing the issue.

Probably, maybe this fixes it:
![image](https://user-images.githubusercontent.com/80113062/179396127-698451f0-d48e-43b0-a6c0-9173ee757df8.png)

**Comment by redromnon** [comment]
That is correct. 
`os.path.isdir()` just checks if that dir is present. But the catch is, your current path [`os.getcwd()`] should match it when you are executing HBL. But instead, it's being redirected to `/opt/games/heroic/javalsai/HeroicBashLauncher` because of that symlink. This should not happen.

**Comment by javalsai** [comment]
If you tell me how to compile the project I can try it

**Comment by redromnon** [comment]
You can follow this - https://github.com/redromnon/HeroicBashLauncher#building-and-testing and change the dir check code accordingly to support your symlink.
