### ISSUE TITLE
[Bug] steam deck HZD won’t load 

### ISSUE THREAD

**Issue by 6foutz4** [redromnon/HeroicBashLauncher#93]
Hey guys,

first post here, and I am very very new to Linux OS. I have a steam deck and have used heroic games launcher to download HZD through epic game store. I can’t get the game to run. I click play it thinks for a moment then aborts. Depending on which compatibility layer I am using (not sure that describes them correctly) I get different errors. HZD doesn’t like proton, it says that it is a 32 bit gaming running on 64 bit protocol and that I need the correct prefix. I looked and couldn’t find any. 

Lutrix does the best but here is a screen shot of the logs. I have googled and looked for Canberra-gtk-module but don’t know where to find it or how to update it. 
![image](https://user-images.githubusercontent.com/110074435/181143716-1eef9f2e-ec19-494b-bec9-03e72cff0426.jpg)
![image](https://user-images.githubusercontent.com/110074435/181143749-cb496ce0-210f-42f7-9a3b-78c800655900.jpg)

**Comment by redromnon** [comment]
I believe you've posted an issue (and log) related to Heroic. This repository is specifically for Bash Launcher issues.
There's something wrong with Winetricks - it's either not installed or corrupted. You can get help at [Heroic Games Launcher](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues) or on Heroic's Discord channel.
