### ISSUE TITLE
[Bug] Crashing on first run, 

### ISSUE THREAD

**Issue by Krzd-OG** [redromnon/HeroicBashLauncher#95]
**Describe the bug**
Process failed, according to the log (which spawned in the main folder, not log folder) it crashed after the third game.
It did not add anything to my steam library.

Logfile is attached.

 - Platform: Desktop
 - OS: Mint 20.2 x86_64
 - Kernel: 5.15.0-41-generic 
 - Heroic Version: v2.3.9 AppImage
 - Bash Launcher Version: v2.8.1

[HeroicBashLauncher.log](https://github.com/redromnon/HeroicBashLauncher/files/9221997/HeroicBashLauncher.log)

**Comment by redromnon** [comment]
Is while True: learn() marked installed in Heroic? Try to launch the game directly via Heroic first.

**Comment by redromnon** [comment]
Will be closing this issue soon due to inactivity.
