### ISSUE TITLE
[Bug]kingdom hearts 0.2 won't launch descriptor error  

### ISSUE THREAD

**Issue by The-Math-God** [redromnon/HeroicBashLauncher#97]
pretty simple whenever i try to launch it from steam i get this 
![thumbnail](https://user-images.githubusercontent.com/41482138/184251198-07b66558-fe62-4efb-a07c-72aff83f4cc8.jpg)

i've tried like 5 different proton ge versions all result in the same thing 
and i know its not a launcher issue because i was able to get DDD running just fine

**Comment by redromnon** [comment]
You can take a look at the logs (`HeroicBashLauncher/GameFiles/logs/game.log`) and try if you spot any errors. 
Is it launching from Heroic directly?

**Comment by redromnon** [comment]
Looks like a game-specific issue to me but I may be wrong.

**Comment by The-Math-God** [comment]
no game-specific otherwise DDD would have the same issue 
and no I'm launching it directly from steam

**Comment by redromnon** [comment]
Can you confirm if it launches from Heroic directly? If yes, it may be a Bash Launcher-only issue.

**Comment by redromnon** [comment]
Will be closing this soon due to inactivity.
